### ISSUE TITLE
Unable to set Kafka consumer property 

### ISSUE THREAD

**Issue by terancet** [spring-cloud/spring-cloud-stream-binder-kafka#1007]
```
spring:
  application:
    name: some_name
  kafka:
    consumer:
      group-id: ${spring.application.name}
      client-id: ${spring.application.name}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
        bindings:
          binding-0:
            max.partition.fetch.bytes: 2000000
      bindings:
        dlq:
          group: ${spring.application.name}
          destination: some_topic_dlq
          producer:
            use-native-encoding: true
        binding-0:
          group: ${spring.application.name}
          destination: some_topic_2
          contentType: application/text
        binding-1:
          group: ${spring.application.name}
          destination: some_topic_1
          contentType: application/text

```

build.gradle
```
dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR9'
    }
}
dependencies {
       implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
}
```
When I set the the following property `max.partition.fetch.bytes` per documentation https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_apache_kafka_binder.html

I dont see that this value has been applied since I can see the following output in the logs: 

```
max.partition.fetch.bytes = 1048576
```

**Comment by garyrussell** [comment]
It's in the wrong place; see https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_apache_kafka_binder.html#_kafka_consumer_properties


>`spring.cloud.stream.kafka.bindings.<channelName>.consumer`

>`configuration`

>Map with a key/value pair containing generic Kafka consumer properties.

>Default: Empty map.

**Comment by terancet** [comment]
```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
        bindings:
          binding-1:
            consumer:
              configuration:
                max.partition.fetch.bytes: 2000000
      bindings:
        binding-dlq:
          group: ${spring.application.name}
          destination: binding-dlq
          producer:
            use-native-encoding: true
        binding-0:
          group: ${spring.application.name}
          destination: binding-0-destination
          contentType: application/text
        binding-1:
          group: ${spring.application.name}
          destination: binding-1-destination
          contentType: application/text
```

Sorry, no luck since I can see in the logs the following output: 

```
13:43:05.192 [main] INFO  org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
	....
	max.partition.fetch.bytes = 1048576
```

**Comment by terancet** [comment]
I played around with the configurations (basically, inserted the `max.partition.fetch.size` whenever is possible =) ) and this config setup seems like produces me the valid results

```
spring:
  kafka:
    consumer:
      group-id: ${spring.application.name}
      client-id: ${spring.application.name}
    properties:
      max.partition.fetch.bytes: 3
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
      bindings:
        binding-dlq:
          group: ${spring.application.name}
          destination: binding-dlq
          producer:
            use-native-encoding: true
        binding-1:
          group: ${spring.application.name}
          destination: binding-1-destination
          contentType: application/text
```

i.e. I can see in the logs the following output

```
13:43:05.192 [main] INFO  org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
	....
	max.partition.fetch.bytes = 3
```

**Comment by garyrussell** [comment]
The properties are applies hierarchically - Boot global props -> superseded by binder props -> superseded by binding props.

This works exactly as expected:

```yaml
spring:
  kafka:
    consumer:
      properties:
        max.partition.fetch.bytes: 1
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            max.partition.fetch.bytes: 2
        bindings:
          consume-in-0:
            consumer:
              configuration:
                max.partition.fetch.bytes: 3
```

You get 3, when the binding prop is commented out you get 2, when the binder prop is commented out you get 1.
