### ISSUE TITLE
KTable not deduplicating the incoming records with same keys

### ISSUE THREAD

**Issue by surysharma** [spring-cloud/spring-cloud-stream-binder-kafka#1073]
I am trying to deduplicate the records using input topic as KTable and sinking them to output topic. But the KTable is still sinking the duplicate records to the output topic. 

Here is my application.yml
```
spring:
  cloud:
    stream:
      function:
        bindings:
          process-in-0: input.topic
          process-out-0: output.topic
        definition: process
      kafka:
        streams:
          bindings:
            process-in-0:
              consumer:
                materializedAs: incoming-store
          binder:
            application-id: spring-cloud-uppercase-app
            brokers: localhost:9092
            configuration:
              commit:
                interval:
                  ms: 1000
                state.dir: state-store
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
```
As per the [spring cloud stream kafka stream documentation about state store](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.1.1/reference/html/spring-cloud-stream-binder-kafka.html#_state_store), I have added the materialized view above as **incoming-store**

The process() bean function takes the input topic as KTable and and sink it to output topic

    @Bean
    public Function<KTable<String, String>, KStream<String, String>> process(){
        return table -> table
                .toStream()
                .peek((k, v) -> log.info("Received key={}, value={}", k, v));
    }

For a given input of 4 records

key=111, value="a"
key=111, value="a"
key=222, value="b"
key=111, value="a"
I am expecting to get only 2 records

key=111, value="a"
key=222, value="b"

But getting all the 4 records.
