### ISSUE TITLE
Unable to start processor when using KTable as output

### ISSUE THREAD

**Issue by selcuksert** [spring-cloud/spring-cloud-stream-binder-kafka#1085]
**Describe the issue**

For a `BiFunction` processor (also reproducible for `Function` processors) that outputs `KTable`, the processor bean cannot be initialized due to class cast exception:
```

Caused by: java.lang.ClassCastException: class org.apache.kafka.streams.kstream.internals.KTableImpl cannot be cast to class org.apache.kafka.streams.kstream.KStream (org.apache.kafka.streams.kstream.internals.KTableImpl and org.apache.kafka.streams.kstream.KStream are in unnamed module of loader 'app')
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsFunctionProcessor.setupFunctionInvokerForKafkaStreams(KafkaStreamsFunctionProcessor.java:322) ~[spring-cloud-stream-binder-kafka-streams-3.1.3.jar:3.1.3]
``` 

**Version of the framework**

```xml
<dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>2020.0.3</version>
</dependency>

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
        <version>3.1.3</version>
</dependency>
```

**Expected behavior**
The processor should start. It was working with `org.springframework.cloud:spring-cloud-stream-binder-kafka-streams:3.0.12.RELEASE`

**Additional context**

The processor snippet:
```java
  @Bean
  public BiFunction<KStream<String, Task>, GlobalKTable<String, User>, KTable<String, DetailedTask>> detail() {
      return (taskStream, userTable) ->
              taskStream.leftJoin(userTable, (key, task) -> task.getUserid(), (task, user) -> {
                  DetailedTask dt = new DetailedTask();
                  dt.setFirstname(user.getFirstname());
                  dt.setLastname(user.getLastname());
                  dt.setDetails(task.getDetails());
                  dt.setDuedate(task.getDuedate());
                  dt.setId(task.getId());
                  dt.setTitle(task.getTitle());
                  dt.setStatus(task.getStatus());
                  return dt;
              }).transformValues(TaskHeaderTransformer::new).toTable(Materialized.as(detailTable));

    @Bean
    public Function<KStream<String, Task>, KTable<String, Long>> activity() {
        return (taskStream) -> {
            KTable<String, Long> taskCount = taskStream
                    .filter((taskId, task) -> task != null)
                    .map((taskId, task) -> KeyValue.pair(task.getUserid(), task))
                    .groupByKey()
                    .windowedBy(TimeWindows.of(Duration.ofHours(1)))
                    .count().toStream().map((userId, task) -> KeyValue.pair(userId.key(), task))
                    .toTable(Materialized.<String, Long, KeyValueStore<Bytes, byte[]>>as(countTable)
                            .withKeySerde(Serdes.String())
                            .withValueSerde(Serdes.Long()));

            if (log.isDebugEnabled()) {
                taskCount.toStream().peek((k, v) -> log.debug("Task Count: {}->{}", k, v));
            }

            return taskCount;
        };
    }

```

Configuration:
```yml
spring:
  cloud:
    stream:
      function:
        definition: detail;activity
      bindings:
        detail-in-0:
          destination: tasks
          consumer:
            use-native-decoding: true
        detail-in-1:
          destination: users
          consumer:
            use-native-decoding: true
            materialized-as: user-table
        activity-in-0:
          destination: tasks
          consumer:
            use-native-decoding: true
```

As the `result` was casted with `KStream`, following snippet causes `ClassCastException` for output bindings of KTable:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/9e4a1075d437f2e6aa7dad0a38d8286de94234a4/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsFunctionProcessor.java#L322

Is there a new/known limitation on using output binding of `KTable` with the new version of binder?
