### ISSUE TITLE
Add batchMode value in ContainerProperties

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-cloud/spring-cloud-stream-binder-kafka#1087]
I want to get the batchMode value from `ListenerContainerCustomizer`.
But I can't determine the batchMode from ContainerProperties .
Could you pass the `extendedConsumerProperties' batchMode` value to ContainerProperties ?

**Comment by garyrussell** [comment]
`batchMode` is not a property of the listener container, it is a property of the listener (inside the message driven channel adapter that uses the container).

You can get the `batchMode` property for a given binding via the application context's `Environment` bean.

**Comment by mhyeon-lee** [comment]
In my case, if BatchMode Consumer is set in ListenerContainerCustomizer , I want to set another setting in MessageListenerContainer. (non-transactioin consumer and batchErrorHandler)

```java
@Bean
ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> listenerContainerCustomizer() {
    return (container, topic, group) -> {
        if ( ... batch mode ...) {
            container.getContainerProperties().setTransactionManager(null);

            RecoveringBatchErrorHandler errorHandler = ....
            container.setBatchErrorHandler(errorHandler); 
        } else {
               // record consumer
        }
    };
}
```

But it's hard to determine if the setting of MessageListenerContainer is BatchMode.
topic can be a different value depending on application.yml profile .

```yml
application-local.yml

spring:
  cloud:
    stream:
      bindings:
        a-consumer-channel:      # channel
          group: a-consumer-group-local   # group
          destination: a-consumer-local.     # topic 
          consumer:
            batch-mode: true
```

```yml
application-beta.yml

spring:
  cloud:
    stream:
      bindings:
        a-consumer-channel:    # channel
          group: a-consumer-group-beta # group
          destination: a-consumer-beta.    # topic
          consumer:
            batch-mode: true
```

It seems that I can get the batchMode value in Environment to know the channel information.
```java
environment.getProperty("spring.cloud.stream.bindings." + channelName + ".consumer.batch-mode");
``` 

Is there a proper way to determine the BatchMode in the Listener Container Customizer?

**Comment by garyrussell** [comment]
Unfortunately, the binding name is not available directly, you would have to add another property.

Something like this:

```yaml
batch-mode:
  for:
    a-consumer-beta:
      a-consumer-group-beta: ${spring.cloud.stream.bindings.a-consumer-channel.consumer.batch-mode}
```

```java
@Bean
ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> listenerContainerCustomizer(Environment env) {
    return (container, topic, group) -> {
        if (isBatchMode(topic, group, env)) {
            container.getContainerProperties().setTransactionManager(null);

            RecoveringBatchErrorHandler errorHandler = ....
            container.setBatchErrorHandler(errorHandler); 
        } else {
               // record consumer
        }
    };
}
```

**Comment by mhyeon-lee** [comment]
@garyrussell 
Thanks for the guide.

Could you add a non transactional setting to the consumer binding property?
kind of `spring.cloud.stream.kafka.bindings.{output-channel}.producer.allowNonTransactional`

**Comment by garyrussell** [comment]
Similar to the `ListenerContainerCustomizer`, there is a `ProducerMessageHandlerCustomizer` but, unfortunately, it's currently only supported by the RabbitMQ binder.

If it was supported by the kafka binder you could use `(handler, dest) -> handler.getKafkaTemplate().set....`.

We can repurpose this issue to add support for that.

**Comment by mhyeon-lee** [comment]
@garyrussell 
I don't want the transaction to be set in the ListenerConsumer when in Batch Mode.

https://github.com/spring-projects/spring-kafka/blob/0ee2d49ea525de038d315bc243b62f1004a26dc6/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L722

https://github.com/spring-projects/spring-kafka/blob/0ee2d49ea525de038d315bc243b62f1004a26dc6/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L933-L954

I think it would be helpful if it could be supported to configure like below.

```yml
spring:
  cloud:
    stream:
      kafka:
        binder:
          transaction:
            transaction-id-prefix: ${random.uuid}
      bindings:
        a-consumer-channel:
          group: a-consumer-group
          destination: a-consumer
          consumer:
            batch-mode: true      # batchMode & non-transaction consumer
            allowNonTransactional: true
        b-consumer-channel:
          group: b-consumer-group
          destination: b-consumer
          consumer:
            batch-mode: false     # recordMode & transaction consumer
            # allowNonTransactional: false
```
