### ISSUE TITLE
cannot fully disable kafka binder and cloud stack for testing

### ISSUE THREAD

**Issue by JohnnyXavier** [spring-cloud/spring-cloud-stream-binder-kafka#1089]
hi,
we are using

```xml
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-stream-kafka</artifactId>
        <version>${spring-cloud-stream-binder-kafka.version}</version> //3.1.3
      </dependency>
```

When running tests the **AdminClient** (and the larger cloud stack) attempts to init on every test.
We do have an **application.yaml** with a kafka binder configured which is the one tests are trying to connect to.

The **AdminClient** tries to connect to a broker that does not exist, consequently failing to create consumers, admin client, etc and adding a lot of time until finally timing out.

Given that not all tests are about testing broker behavior this causes a lot of delay, mostly locally when trying to unit test certain behavior unrelated to brokers.

I tried to exclude kafka and cloud autoconfigurations without success
these are the ones I took out starting with KafkaAutoConfiguration alone and then adding the rest 1 by 1.

```yaml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration
      - org.springframework.cloud.stream.config.BindingsEndpointAutoConfiguration
      - org.springframework.cloud.stream.config.ChannelBindingAutoConfiguration
      - org.springframework.cloud.stream.config.ChannelsEndpointAutoConfiguration
      - org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration
```
also tried excluding them via code:

```java
@SpringBootApplication( exclude = {KafkaAutoConfiguration.class, .........})
```

even with all those out the **KafkaAutoconfiguration** keeps getting beaned in as well as **KafkaBinderConfiguration**

I also tried to exclude non autoconfigurations beans as **KafkaBinderConfiguration**,  **KafkaBinderHealthIndicatorConfiguration**, **DefaultBinderFactory**, without success.

I could not find a way to fully disable the cloud stack as some dependency keeps pulling Kafka and binder back in and KafkaAutoconfiguration keeps getting called

----

I finally "hacked" a solution by making the attempt to connect fail fast like this

``` yaml
  cloud:
    stream:
      kafka:
        binder:
          brokers:
```

which makes the **AdminClient** to fail immediately on an empty broker and we don't have to wait for the cloud stack to timeout.

```
2021-06-11 08:59:34,114 [main] INFO  org.springframework.cloud.stream.binder.DefaultBinderFactory - Creating binder: kafka
2021-06-11 08:59:34,329 [main] INFO  org.springframework.cloud.stream.binder.DefaultBinderFactory - Caching the binder: kafka
2021-06-11 08:59:34,330 [main] INFO  org.springframework.cloud.stream.binder.DefaultBinderFactory - Retrieving cached binder: kafka
2021-06-11 08:59:34,408 [main] INFO  org.apache.kafka.clients.admin.AdminClientConfig - AdminClientConfig values: 
	bootstrap.servers = []
```

Seems there should be a way to completely exclude the cloud stack so it won't load any beans related to binders, channels, kafka, etc

the first one I can see gets called is
```
2021-06-11 09:07:36,266 [main] INFO  org.springframework.integration.config.DefaultConfiguringBeanFactoryPostProcessor - No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
```

Can u advise if this is by design?

Is it possible to include a "**_CloudAutoconfiguration_**" bean that will be at the top of init of the rest of the stack so we can disable it completely maybe like this:?

``` yaml
  cloud:
      disabled: true
```

Thanks a lot.
