### ISSUE TITLE
Add support for LZ4 compression in producer

### ISSUE THREAD

**Issue by osialr** [spring-cloud/spring-cloud-stream-binder-kafka#110]
`org.apache.kafka.common.record.CompressionType` supports lz4 but I cannot specify it within kafka binder properties.  

It appears that the enum `KafkaProducerProperties.CompressionType` only has `none`, `gzip`, and `snappy`

My configuration includes 
```
spring:
  cloud:
    stream:
      kafka:
        bindings:
          ResultItemOutput:
            producer:
              compressionType: lz4
      bindings: 
        ResultItemOutput:
          destination: ResultItem
```

And spring error is
```

Binding to target org.springframework.cloud.stream.binder.kafka.properties.KafkaExtendedBindingProperties@3ac406d4 failed:

    Property: spring.cloud.stream.kafka.bindings[ResultItemOutput].producer.compressionType
    Value: lz4
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.cloud.stream.binder.kafka.properties.KafkaProducerProperties$CompressionType' for property 'bindings[ResultItemOutput].producer.compressionType'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@javax.validation.constraints.NotNull org.springframework.cloud.stream.binder.kafka.properties.KafkaProducerProperties$CompressionType] for value 'lz4'; nested exception is java.lang.IllegalArgumentException: No enum constant org.springframework.cloud.stream.binder.kafka.properties.KafkaProducerProperties.CompressionType.lz4
```
