### ISSUE TITLE
DlqDestinationResolver not working using functional style

### ISSUE THREAD

**Issue by jdeex** [spring-cloud/spring-cloud-stream-binder-kafka#1108]
We have set enableDlq: true, and created a @Bean DlqDestinationResolver, but when we use functional consumers, the binder ignores our bean and tries to send the error messages to the standard DLQ topic

We are using Spring Boot 2.4.8, Spring Cloud 2020.0.3 and Kafka Binder 3.1.3

**Comment by sobychacko** [comment]
@jdeex I quickly tested an application and it works fine with `DlqDestinationResolver`. It still creates the standard DLQ topic though, which might be something that we need to clean up. Here is what I tested this with.

```
@Bean
public Consumer<Message<String>> consume() {
    return s -> {
	    throw new RuntimeException();
    };
}

@Bean
public DlqDestinationResolver dlqDestinationResolver() {
    return (t, u) -> "custom-dlq-resolver";
}
```

```
spring.cloud.stream.bindings:
  consume-in-0:
    destination: my-input-topic
    group: my-group

spring.cloud.stream.kafka.bindings.consume-in-0.consumer.enableDlq: true

```
