### ISSUE TITLE
auto-create-topics does not set allow.auto.create.topics property

### ISSUE THREAD

**Issue by rvinzent** [spring-cloud/spring-cloud-stream-binder-kafka#1113]
Setting the `spring.cloud.stream.kafka.binder.autoCreateTopics` property does not seem to have any effect on the consumer configuration property `allow.auto.create.topics`

Config:
```yaml
spring.cloud:
  function.definition: process
  stream:
    default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092}
          autoCreateTopics: false
```

Log output:
```
2021-08-02 12:06:00.485  INFO 65323 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	allow.auto.create.topics = true
```

There are no other overrides to consumer properties. Is this intentional behavior?
