### ISSUE TITLE
Functional style does not support producer serdes

### ISSUE THREAD

**Issue by jomach** [spring-cloud/spring-cloud-stream-binder-kafka#1116]
Hey, 

I have a app with the following config: 
```
spring.cloud.stream.bindings.process-in-1:
  destination: dev.md.V_ED_MATERIAL_COMPOSITION
spring.cloud.stream.bindings.process-out-0:
  destination: dev.md.MATERIAL3
  producer-properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        key.serializer: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
        value.serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  deserializationExceptionHandler: logAndFail
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    commit.interval.ms: 1000
```

Instead of producer-properties I tried producer, producerProperties nothing works.  My code is using a BiFunction to return a stream that I want to serialized it a json.
Following this https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#_kafka_streams_producer_properties does not work too
