### ISSUE TITLE
Classpath reference doesn't work for arbitrary consumerProperties

### ISSUE THREAD

**Issue by eduardolbueno** [spring-cloud/spring-cloud-stream-binder-kafka#1170]
Currently using:

spring-boot 2.5.3
spring-cloud 2020.0.3 (spring-cloud-starter-stream-kafka 3.1.3)

I have a scenario where I need to use a JKS certificate to connect both to Kafka and to the Schema registry. I have declared properties like so:

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
            security:
              protocol: SSL
            ssl:
              truststore:
                type: JKS
                location: classpath:certs/mycert-app.jks
                password: myapp
              keystore:
                type: JKS
                location: classpath:certs/mycert.jks
                password: myapp
          consumerProperties:
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: classpath:certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: classpath:certs/mycert.jks
                    password: myapp
```

The problem is that the `classpath:` reference only works for the Kafka connection itself. It doesn't work for the Schema, throwing a `java.io.FileNotFoundException: classpath:certs/mycert.jks (No such file or directory)`. 
It works though with an absolute path, like `/Users/eduardolbueno/workspace/myapp/src/main/resources/certs/mycert.jks` but that is subpotimal for cloud environments.
Can I reference the classpath cert in another way?
