### ISSUE TITLE
Use of @EmbeddedKafka with Kafka Streams binder

### ISSUE THREAD

**Issue by ecristobal** [spring-cloud/spring-cloud-stream-binder-kafka#1192]
Good morning!

I'm having issues when I try to run a test with @EmbeddedKafka with KStreams, so I need your help to make it work.

This is my current test class:

```java
@TestInstance(Lifecycle.PER_CLASS)
@ExtendWith(SpringExtension.class)
@DirtiesContext
@SpringBootTest
@EmbeddedKafka(bootstrapServersProperty = "spring.cloud.stream.kafka.streams.binder.brokers",
               topics = { "input-topic", "output-topic" },
               brokerProperties = { "listeners=PLAINTEXT://localhost:9092", "port=9092" })
class StreamFunctionIT {

    @Value("${spring.cloud.stream.bindings.enrich-in-0.destination}")
    private String inputTopic;

    @Value("${spring.cloud.stream.bindings.enrich-out-0.destination}")
    private String outputTopic;

    @Autowired
    private EmbeddedKafkaBroker embeddedKafkaBroker;

    private BlockingQueue<ConsumerRecord<UUID, ValueResponse>> records;
    private KafkaMessageListenerContainer<UUID, ValueResponse> container;
    private Producer<UUID, ValueRequest> producer;

    @BeforeAll
    void setUp() {
        // Consumer set-up
        final Map<String, Object> consumerConfig =
                new HashMap<>(KafkaTestUtils.consumerProps("enricher", "false", this.embeddedKafkaBroker));
        final DefaultKafkaConsumerFactory<UUID, ValueResponse> consumerFactory =
                new DefaultKafkaConsumerFactory<>(consumerConfig, new Serdes.UUIDSerde().deserializer(),
                        new JsonSerde<>(ValueResponse.class).deserializer());
        final ContainerProperties containerProperties = new ContainerProperties(this.outputTopic);
        this.container = new KafkaMessageListenerContainer<>(consumerFactory, containerProperties);
        this.records = new LinkedBlockingQueue<>();
        this.container.setupMessageListener((MessageListener<UUID, ValueResponse>) this.records::add);
        this.container.start();
        ContainerTestUtils.waitForAssignment(this.container, this.embeddedKafkaBroker.getPartitionsPerTopic());
        // Producer set-up
        final Map<String, Object> producerConfig =
                new HashMap<>(KafkaTestUtils.producerProps(this.embeddedKafkaBroker));
        this.producer = new DefaultKafkaProducerFactory<>(producerConfig, new Serdes.UUIDSerde().serializer(),
                new JsonSerde<>(ValueRequest.class).serializer()).createProducer();
    }

    @AfterAll
    void tearDown() {
        this.container.stop();
    }

    @Test
    void testEnrich() throws InterruptedException {
        this.records.clear();
        // Create message key and value
        this.producer.send(new ProducerRecord<>(this.inputTopic, UUID.randomUUID(), value));
        final ConsumerRecord<UUID, ValueResponse> output = this.records.poll(10, TimeUnit.SECONDS);
        // Assertions
    }

}
```

This is my YAML configuration:

```yaml
spring:
  cloud:
    stream:
      function:
        definition: enrich
      bindings:
        enrich-in-0:
          destination: input-topic
        enrich-out-0:
          destination: output-topic
      kafka:
        streams:
          binder:
            functions:
              enrich:
                applicationId: enricher
          bindings:
            enrich-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
                valueSerde: org.springframework.kafka.support.serializer.JsonSerde
            enrich-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
                valueSerde: org.springframework.kafka.support.serializer.JsonSerde
```

This is the Spring Cloud Stream bean definition:

```java
@Configuration
class StreamConfiguration {

    @Bean
    Function<KStream<UUID, ValueRequest>, KStream<UUID, ValueResponse>> enrich(
            final EnrichService<ValueRequest, ValueResponse> enrichService) {
        return input -> input.mapValues(enrichService::enrich);
    }

}
```

And this is my pom.xml (only relevant dependencies included):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.2</version>
        <relativePath/>
    </parent>
    <groupId>com.example.kstream</groupId>
    <artifactId>message-enricher</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>
        <spring-cloud-stream.version>3.2.1</spring-cloud-stream.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
            <version>${spring-cloud-stream.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
            <version>${spring-cloud-stream.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

```

When I run my tests, the request message is sent to the input topic, but the "enrich" function does not read it, so I'm guessing that I'm missing some of the configuration to make it work properly (I've made an equivalent test using Kafka binder and everything works as expected).

Thank you very much for your time and support!
