### ISSUE TITLE
Unable to pass consumer configuration to Kafka

### ISSUE THREAD

**Issue by stphngrtz** [spring-cloud/spring-cloud-stream-binder-kafka#240]
`org.springframework.cloud.stream.binder.kafka.properties.KafkaConsumerProperties#setConfiguration` is never getting called.

**Comment by garyrussell** [comment]
In future, please be much more explicit when reporting potential problems.

Now, why do you expect that method to be called?

When you set an arbitrary kafka property using the `....configuration` key, the framework sets the property by calling `getConfiguration()` and then adds the property to that map...

    spring.cloud.stream.kafka.bindings.input.consumer.configuration.client.id=myClientId

result...

    2017-10-27 10:00:37.722  INFO 12276 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	auto.commit.interval.ms = 100
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.id = myClientId-0
        ...

(Note that spring-kafka appends a qualifier to the client id in order to support multiple concurrent consumers).

**Comment by stphngrtz** [comment]
Sorry for not adding enough details to the issue.

I did the following configuration:
```yml
spring:
  cloud:
    stream:
      ...
      kafka:
        ...
        bindings:
          my-topic:
            configuration:
              maxPollRecords: 1
              dummy: my-dummy
```

With a breakpoint at `org.apache.kafka.clients.consumer.KafkaConsumer#KafkaConsumer(org.apache.kafka.clients.consumer.ConsumerConfig, org.apache.kafka.common.serialization.Deserializer<K>, org.apache.kafka.common.serialization.Deserializer<V>)` I saw that the parameter `config` is missing `maxPollRecords` as well as `dummy`. I've followed this back to `org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder#createKafkaConsumerFactory` and thought that the following condition should be true, but is not.

```java
if (!ObjectUtils.isEmpty(consumerProperties.getExtension().getConfiguration())) {
    props.putAll(consumerProperties.getExtension().getConfiguration());
}
```

`spring-cloud-stream-binder-kafka` is added to my project in version `1.2.1.RELEASE`

**Comment by garyrussell** [comment]
These are raw kafka properties; kafka doesn't understand camelCase; use

```yaml
spring:
  cloud:
    stream:
      kafka:
        bindings:
          input:
            consumer:
              configuration:
                max.poll.records: 23
```

or

```yaml
spring:
  cloud:
    stream:
      kafka:
        bindings:
          input:
            consumer:
              configuration:
                max:
                  poll:
                    records: 23
```

**Comment by stphngrtz** [comment]
Ah okay, thank you. But shouldn't I be able to at least see the configuration options at my breakpoint, even if `maxPollRecords` will not be considered because of camel case?

**Comment by garyrussell** [comment]
I can see them all in my debugger...

![screen shot 2017-10-27 at 12 15 59 pm](https://user-images.githubusercontent.com/483832/32114159-ab0ceb66-bb10-11e7-9b0f-48287512a1e4.png)

**Comment by stphngrtz** [comment]
Sorry, but this is still not working for me. I've created [a simple example repository](https://github.com/stphngrtz/spring-cloud-stream-binder-kafka-issue-240):
- https://start.spring.io/
- added `Stream Kafka`
- added `@EnableBinding(Sink.class)`
- changed `application.properties` to `application.yml`
- provided [a configuration](https://github.com/stphngrtz/spring-cloud-stream-binder-kafka-issue-240/blob/master/src/main/resources/application.yml)

As you can see, my custom configuration is not getting passed on to Kafka.

```
2017-11-02 09:03:05.771  INFO 9084 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	auto.commit.interval.ms = 100
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9094]
	check.crcs = true
	client.id = consumer-2
	connections.max.idle.ms = 540000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = anonymous.9e662234-af6b-4ad0-8765-0a80256a9d94
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
```

Could you give me a hint what I'm doing wrong?

**Comment by usopan** [comment]
I am also facing a similar issue, unable to set value.deserializer

**Comment by jmax01** [comment]
We too are having this issue in 1.3.2.

We can't set `autoCommitOffset`.

It appears that the `KafkaConsumerProperties` is not being populated.

The `KafkaConsumerProperties` returned from `KafkaExtendedBindingProperties.getExtendedConsumerProperties` is never populated.

**Comment by olegz** [comment]
@stphngrtz There is an issue with your configuration. 
I just looked at it and it appears you have missed a `consumer` segment. After fixing it and taking part of your configuration I can see all properties being passed. See below
```
spring:
  cloud:
    stream:
      kafka:
        bindings:
          input:
            consumer:
              configuration:
                max.poll.records: 23
                dummy: my-dummy
                metadata.max.age.ms: 300001
                auto.commit.interval.ms: 101
```
Output:
```
2018-03-05 19:12:14.861  INFO 90006 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
auto.commit.interval.ms = 101
auto.offset.reset = latest
bootstrap.servers = [localhost:9092]
. . .
metadata.max.age.ms = 300001
metric.reporters = []
. . .
2018-03-05 19:12:14.864  WARN 90006 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'dummy' was supplied but isn't a known config.
2018-03-05 19:12:14.864  INFO 90006 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 1.0.0
```
