### ISSUE TITLE
Support for KStream branch and split

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#265]
Right now there is no way to bind multiple outbound KStream target types in KStream binder. We should provide support for branching and split into various output topics. 

See this: https://kafka.apache.org/0100/javadoc/org/apache/kafka/streams/kstream/KStream.html#branch(org.apache.kafka.streams.kstream.Predicate...)

See the original issue: https://github.com/spring-cloud/spring-cloud-stream/issues/1141

**Comment by kmandalas** [comment]
The native KStream API gives the ability of branching an incoming Stream to an Array or resulting Streams based on Predicates: 
- https://kafka.apache.org/0100/javadoc/org/apache/kafka/streams/kstream/KStream.html#branch(org.apache.kafka.streams.kstream.Predicate...)

Each of the resulting streams of the Array can be further redirected (materialized) to a number of different output topics using the following method (which is overloaded, below you may find the simplest form):

- https://kafka.apache.org/0100/javadoc/org/apache/kafka/streams/kstream/KStream.html#to(java.lang.String)

Notice that the `to()` methods above return `void`.

Now, currently the `KStreamProcessor` interface, declares one Input and one Output channel. Theoretically, as @mbogoevici has mentioned (see https://github.com/mbogoevici/spring-cloud-stream-binder-kstream), if we extend this interface, we can add more output channels and more than one `StreamListeners`. However I am not sure if this finally supported and to which extend. For example is it possible to use `org.springframework.cloud.stream.annotation.StreamListener#condition`?

**Comment by xmlking** [comment]
we can make it works, but we need to have a dummy output topic (e.g., retention.ms=100)

```kotlin
import org.apache.kafka.streams.KeyValue
import org.apache.kafka.streams.kstream.KStream
import org.apache.kafka.streams.kstream.TimeWindows
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.cloud.stream.annotation.EnableBinding
import org.springframework.cloud.stream.annotation.StreamListener
import org.springframework.cloud.stream.binder.kstream.annotations.KStreamProcessor
import org.springframework.context.annotation.Configuration
import org.springframework.messaging.handler.annotation.SendTo
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import org.apache.kafka.streams.kstream.Predicate
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value

@SpringBootApplication
@EnableBinding(KStreamProcessor::class)
class AnalyzerApplication

fun main(args: Array<String>) {
    SpringApplication.run(AnalyzerApplication::class.java, *args)
}

@Configuration
class LogProcessor(
    val timeWindows: TimeWindows, val mapper: ObjectMapper,
    @Value(value = "\${app.kafka.topic.peg}") private val pegTopic: String,
    @Value(value = "\${app.kafka.topic.call}") private val callTopic: String,
    @Value(value = "\${app.kafka.topic.error}") private val errorTopic: String) {

    private val log = LoggerFactory.getLogger(LogProcessor::class.java)

    @StreamListener("input")
    @SendTo("output")
    fun splitStrings(input: KStream<*, Log>): KStream<*, Log> {

        if(log.isDebugEnabled) {
            input.print()
        }

        val logTypeToKey = { _: Any?, v: Log -> v.loggerName }

        val messageToPegLog = { k: String, v: String ->
            val pegLog = mapper.readValue<PegLog>(v)
            KeyValue(k, mapper.writeValueAsString(pegLog))
        }
        val messageToCallLog = { k: String, v: String ->
            val callLog = mapper.readValue<CallLog>(v)
            KeyValue(k, mapper.writeValueAsString(callLog))
        }
        val messageToErrorLog = { k: String, v: String ->
            val errorLog = mapper.readValue<ErrorLog>(v)
            KeyValue(k, mapper.writeValueAsString(errorLog))
        }

        val isPegLog = Predicate({ k: String, _: Log -> k.equals("rptpeg.PegLog") })
        val isCallLog = Predicate({ k: String, _: Log -> k.equals("rptcall.CallLog") })
        val isErrorLog = Predicate({ k: String, _: Log -> k.equals("rpterror.ErrorLog") })

        val filteredStreams = input.selectKey(logTypeToKey).branch(isPegLog, isCallLog, isErrorLog)

        filteredStreams[0].map(messageToPegLog).to(pegTopic)
        filteredStreams[1].map(messageToCallLog).to(callTopic)
        filteredStreams[2].map(messageToErrorLog).to(errorTopic)

        return input
    }

}
```
```yml
spring:
  application:
    name: demo

  cloud:
    stream:
      bindings:
        input:
          destination: app_logs
          consumer:
            headerMode: raw
        output:
          contentType: application/json
          destination: app_logs_duplicate
          producer:
            headerMode: raw
            useNativeEncoding: true

      kstream:
        timeWindow:
          length: 5000
          advanceBy: 0
        binder:
          brokers: 127.0.0.1
          zkNodes: 127.0.0.1
          configuration:
            commit.interval.ms: 1000
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            application.id: demo
```

**Comment by sobychacko** [comment]
@xmlking While this approach works, we lose all the outbound features provided by the framework such as message conversion etc. As you have shown in the example, then it is the application's responsibility to do proper serialization etc. There is a PR in flight that adds branching capability in the KStream binder. Here is the gist of it. You need to provide a `Predicate[]` bean in the context that contains the Predicates in order. Then specify a property:

`spring.cloud.stream.kstream.bindings.output.producer.additionalBranches: foo,bar `

The output branches are whats defined by main output destination and then foo and bar. 

Something like this:

```
@EnableBinding(KStreamProcessor.class)
	@EnableAutoConfiguration
	public static class WordCountProcessorApplication {

		@Autowired
		private TimeWindows timeWindows;

		@StreamListener("input")
		@SendTo("output")
		public KStream<?, WordCount> process(KStream<Object, String> input) {
			return input
					.flatMapValues(value -> Arrays.asList(value.toLowerCase().split("\\W+")))
					.groupBy((key, value) -> value)
					.windowedBy(timeWindows)
					.count(Materialized.as("WordCounts-1"))
					.toStream()
					.map((key, value) -> new KeyValue<>(null, new WordCount(key.key(), value, new Date(key.window().start()), new Date(key.window().end()))));
		}

		@Bean
		public Predicate[] predicates() {
			Predicate<?, WordCount> isEnglish = (k, v) -> v.word.equals("english");
			Predicate<?, WordCount> isFrench =  (k, v) -> v.word.equals("french");
			Predicate<?, WordCount> isSpanish = (k, v) -> v.word.equals("spanish");
			return new Predicate[] {isEnglish, isFrench, isSpanish};
		}

	}
```
and the application.yml

```
spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kstream.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kstream.binder.configuration:
  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.output:
  destination: counts
  producer:
    headerMode: raw
spring.cloud.stream.kstream.bindings.output.producer.additionalBranches: foo,bar
spring.cloud.stream.bindings.input:
  destination: words
  consumer:
    headerMode: raw
spring.cloud.stream.kstream.binder:
  brokers: 192.168.99.100
  zkNodes: 192.168.99.100
```
Here is the PR I mentioned: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/274
