### ISSUE TITLE
Kafka producer config issue

### ISSUE THREAD

**Issue by loicmathieu** [spring-cloud/spring-cloud-stream-binder-kafka#360]
Hello,

I detected a possible kafka producer configuration issue.
I'm using a standard Spring Boot application with Spring Cloud Stream and the kafka Bindings.

I want to configure the producer configuration using the application.yml file, when I configure using the spring.cloud.stream.kafka.binder.configuration it works (it's a Map<String,String>) but when I configure using spring.cloud.stream.kafka.binder.producer-configuration (that is a Map<String, Object>) it crash with the following error : 
```
Failed to bind properties under 'spring.cloud.stream.kafka.binder.producer-configuration' to java.util.Map<java.lang.String, java.lang.Object>:

    Property: spring.cloud.stream.kafka.binder.producer-configuration.buffer.memory
    Value: 33554432
    Origin: class path resource [application.yml]:16:30
    Reason: Failed to bind properties under 'spring.cloud.stream.kafka.binder.producer-configuration' to java.util.Map<java.lang.String, java.lang.Object>
```

As I want to configure producer specific configuration I would prefer to be able to put them in the producer-configuration and not in the configuration that configure both producer and consumer.

A working configuration : 
```
spring:
  cloud:
    stream:      
      kafka:
        binder:
          brokers: ${kafka.brokers}   
          configuration:
            retries: 10
            "linger.ms": 1
            "buffer.memory": 33554432
```
A not working one :
```
spring:
  cloud:
    stream:      
      kafka:
        binder:
          brokers: ${kafka.brokers}    
          producer-configuration:
            retries: 10
            "linger.ms": 1
            "buffer.memory": 33554432
```

I don't know if it's a bug or if I made something wrong ...

Regards,

Loïc

**Comment by olegz** [comment]
I may have seen this before. What version of stream you're using? Also, can you please provide the stack trace?

**Comment by olegz** [comment]
Should it be:
```
spring:
  cloud:
    stream:      
      kafka:
        binder:
          brokers: ${kafka.brokers}    
          environment:
            retries: 10
            . . .
```
???
