### ISSUE TITLE
Unable to configure bootstrap-servers

### ISSUE THREAD

**Issue by f9cus** [spring-cloud/spring-cloud-stream-binder-kafka#388]
Hi,
I created a simple application that takes data from one kafka topic a sends them to another one.
I am unable to configure bootstrap-servers in application.yml to be working properly with ConsumerConfig and ProducerConfig.

I am using boot version 2.0.1.

I tried multiple options, such as:
```yml
spring:
  kafka:
    bootstrap-servers: my.boostrap.host:9092
```

```yml
spring:
  kafka:
    consumer:
      bootstrap-servers: my.boostrap.host:9092
```

```yml
spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            bootstrap-servers: my.boostrap.host:9092
```

```yml
spring:
  cloud:
    stream:
      kafka:
        bindings:
          input:
            consumer:
              configuration:
                bootstrap-servers: my.boostrap.host:9092
```

In console output i can see:

> o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values: 
	bootstrap.servers = [my.boostrap.host:9092]

However bootstrap is not working and further console output for producer/consumer config shows localhost instead of my boostrap server:
> o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [localhost:9092]

> o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [localhost:9092]

My source code can be found here:
https://github.com/f9cus/kafka-help/blob/master/src/main/resources/application.yml

Any help is much appreciated.
Thank you
