### ISSUE TITLE
Error while trying to send a message to a topic with key

### ISSUE THREAD

**Issue by VasuBhaskar** [spring-cloud/spring-cloud-stream-binder-kafka#408]
I am trying to send message to a compacted topic with a key , but i get the error as follows

I have used the messageKeyExpression parameter under 

spring.cloud.stream.kafka.bindings.<channel>.producer.message-key-expression: headers['myKey']

**Error:**

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.stream.kafka.bindings.output1.producer.message-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.kafka.bindings.output1.producer.message-key-expression
    Value: headers['myKey']
    Origin: class path resource [application.yml]:15:39
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

Action:
Update your application's configuration
```

I tried to add a custom converter bean to convert string to Expression but that didnt help as well.

Error can be reproduced with the code at the below repo

https://github.com/VasuBhaskar/springcloud-error-recreate

Any quick help will be much appreciated.

**Comment by olegz** [comment]
I believe your problem is with the packaging structure. The main Spring boot application class doesn't pick up `@EnableBinding` annotation in your `processor` package. . . . which would also register automatically the String to Expression converter (you don't need to define your own. . .

What I would recommend is to configure your processor in your app itself
```
@SpringBootApplication
@EnableBinding(InputSource.class)
class ErrorRecreateApplication {

	static void main(String[] args) {
		SpringApplication.run ErrorRecreateApplication, args
	}
	
	@StreamListener(InputSource.INPUT)
	@SendTo(OutputDestiny.OUTPUT)
	String processMessage(Message<String> event) {
	    log.info('message' + event)
	    //populating the key as 1 just for testing purposes. I have tried with string values as well
	    Message<String> outputMessage = MessageBuilder.withPayload(event.getPayload()).setHeader('myKey', 1).build()
	    log.info('out' + outputMessage)
	    return outputMessage
	}
}
```
Sure your can partition your configuration in other packages, but that may require additional `@Import` annotation.

**Comment by VasuBhaskar** [comment]
@olegz Thanks a lot for the help. I just tried as per your recommendation, but still the same error. I have updated the code now as per your suggestion.

**Comment by sobychacko** [comment]
@VasuBhaskar I noticed that you are using multi kafka binders. If you remove the multi binder configuration and their references, this error goes away. This indicates that the environment created in `kafka-output` is not propagated down to the binder specific extended properties which is where `messateKeyExpression` is. This maybe a bug that needs to be fixed. There could also be a work aroud to this situation. Will look further and update here. In any case, if you are trying out something, you can simply resort to a single binder environment to get past this error until we sort this out.

**Comment by VasuBhaskar** [comment]
@sobychacko i have tried to use a single binder environment now. I have removed the kafka-output binder and used kafka-input in both the places. Still i am facing the same error. I have updated the code as well. Please let me know if my am not correctly interpreting what you have said. Thanks for the quick help!!

**Comment by VasuBhaskar** [comment]
@sobychacko @olegz could you please provide a work around solution for this issue ? we are currently stuck with this issue and unable to move forward. Any quick help will be much appreciated!

**Comment by olegz** [comment]
@VasuBhaskar we'll try to address it shortly, however unfortunately the workaround may be applying the same patch in your local environment

**Comment by sobychacko** [comment]
@VasuBhaskar This configuration works for me (basically remove the multibinder settings for the time being)
```
spring:
  cloud:
    stream:
      kafka:
        bindings:
          input1:
            consumer:
              enableDlq: false
              dlqName: test-dlq
              maxPollRecords: 5
              autoCommitOnError: true
          output1:
            producer:
              sync: true
              messageKeyExpression: headers['myKey']
      bindings:
        input1:
          group: test
          destination: test-topic
          contentType: text/plain
          consumer:
            instanceCount: 10
            headerMode: raw
            partitioned: true
        output1:
          binder: kafka-input
          destination: test-output-topic
          producer:
            headerMode: raw
            useNativeEncoding: true
server:
  port: 8081
```
