### ISSUE TITLE
KStreamBinderConfiguration cannot find KafkaProperties when using multi-binder configuration

### ISSUE THREAD

**Issue by 2speed** [spring-cloud/spring-cloud-stream-binder-kafka#411]
**Environment**
- JDK - 1.8.0_172
- Gradle - 4.8.1
- Spring Boot - 2.0.3.RELEASE
- Spring Cloud Stream - Elmhurst.SR1

**Description**

I ran into an issue similar to spring-cloud/spring-cloud-stream-binder-kafka#326 using Spring Boot with the Kafka streams binder when attempting to bridge a stream from an external Kafka cluster. When running my application, I get the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field kafkaProperties in org.springframework.cloud.stream.binder.kafka.streams.KStreamBinderConfiguration required a bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' in your configuration.
```

**Code**

`build.gradle`
```gradle
buildscript {
	repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://repo.spring.io/plugins-release' }
        maven { url 'https://plugins.gradle.org/m2' }
        mavenLocal()
	}
	dependencies {
		classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.3.RELEASE'
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.esm.stream'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	jcenter()
}

ext {
	springCloudVersion = 'Elmhurst.SR1'
}

dependencies {
    // Spring : Test
    testCompile 'org.springframework.boot:spring-boot-starter-test'
    testCompile 'org.springframework.cloud:spring-cloud-stream-test-support'
    
    // Spring : SCS
    compile 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-stream-dependencies:${springCloudVersion}"
	}
}
```

`application.yml`
```yaml
spring.cloud.stream:
  bindings:
    input:
      binder: kBind1
  binders:
    kBind1:
      type: kstream
      environment:
        spring.cloud.stream.kafka.streams.binder:
          brokers: localhost:9093
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
```

`StreamSourceApplication.java`
```java
package com.esm.stream;

import java.util.Map;

import org.apache.kafka.streams.kstream.KStream;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.Input;
import org.springframework.cloud.stream.annotation.StreamListener;

@SpringBootApplication()
@EnableBinding(com.esm.stream.StreamSourceApplication.StreamSourceProcessor.class)
public class StreamSourceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(StreamSourceApplication.class, args);
    }
    
    @StreamListener
    public void handle(@Input("input") KStream<Object, Map<String, Object>> stream) {
       stream.foreach((k, v) -> {
           System.out.println("\n" + k + ":\n" + v + "\n");
       });
    }
    
    interface StreamSourceProcessor {
        @Input("input")
        KStream<?, ?> inputStream();
    }
}
```

**Comment by 2speed** [comment]
@sobychacko I was attempting to bridge and external Kafka stream to a local one. The code I provided above was what I found to be the minimal to re-produce the error. I updated my code to utilize a multi-binder config and the same error persists:

`application.yml`
```yaml
spring.cloud.stream:
  bindings:
    input:
      binder: kBind1
    output:
      binder: kBind2
  binders:
    kBind1:
      type: kstream
      environment:
        spring.cloud.stream.kafka.streams.binder:
          brokers: external-kafka:9093
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    kBind2:
      type: kstream
      environment:
        spring.cloud.stream.kafka.streams.binder:
          brokers: localhost:9093
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
```

`StreamSourceApplication.java`
```java
package com.esm.stream;

import java.util.Map;

import org.apache.kafka.streams.kstream.KStream;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.Input;
import org.springframework.cloud.stream.annotation.StreamListener;
import org.springframework.messaging.handler.annotation.SendTo;

@SpringBootApplication()
@EnableBinding(com.esm.stream.StreamSourceApplication.StreamSourceProcessor.class)
public class StreamSourceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(StreamSourceApplication.class, args);
    }
    
    @StreamListener("input")
    @SendTo("output")
    public KStream<Object, Map<String, Object>> handle(KStream<Object, Map<String, Object>> stream) {
       return stream.peek((k, v) -> {
           System.out.println("\n" + k + ":\n" + v + "\n");
       });
    }
    
    interface StreamSourceProcessor {
        
        @Input("input")
        KStream<?, ?> inputStream();
        
        @Input("output")
        KStream<?, ?> outputStream();
    }
}
```

Any ideas on a possible workaround?

**Comment by sabbyanandan** [comment]
Depends on spring-cloud/spring-cloud-stream#1420

**Comment by sobychacko** [comment]
@2speed The fixes for this issue are now committed to spring-cloud-stream core (https://github.com/spring-cloud/spring-cloud-stream/commit/daccfb5e588b47b213745acc71e2ecd342138cef) and the kafka binder (https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/418/commits/e03baefbafdd85e367a4abd77f90a3d67ed341da). You may want to check the snapshots.

**Comment by 2speed** [comment]
@sobychacko Will do, thanks!

**Comment by iamdaniu** [comment]
I'm still getting "No qualifying bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' available" with a binder of type 'ktable` or `globalktable` and two separate config files (to be able switch security on/off); Spring Boot 2.1.5.RELEASE, Spring Cloud version Greenwich.SR1 and Cloud Stream Version Fishtown.RELEASE.

`application.yaml`:
```
spring.cloud.stream:
  bindings.cache:
    destination: items-topic
    binder: cache
    group: cache-group
  kafka.streams:
    binder:
      application-id: splitter
      brokers: localhost:9092
      configuration.default:
        key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value.serde: com.example.minfail.SampleSerdes$ItemSerde
    bindings:
      cache.consumer:
        applicationId: cache
        materializedAs: items-cache
  binders.cache.type: globalktable
# changing this to ktable also breaks
```

`application-kerberos.yaml`:
```
spring.cloud.stream:
  kafka.binder.configuration:
    security.protocol: SASL_SSL
    sasl.kerberos.service.name: kafka
    jaas:
      loginModule: com.sun.security.auth.module.Krb5LoginModule
      options:
        useKeytab: true
        storeKey: true
  binders.cache.environment.spring.cloud.stream.kafka.binder.configuration.jaas.options:
    keyTab: cache_keytab
    principal: cache_principal
```
Relevant code:
```
@EnableBinding(CacheBinding.class)
public class ItemCacher {
    @StreamListener
    void materialize(@Input(CacheBinding.ITEMS) GlobalKTable<String, Item> items) {}
}

interface CacheBinding {
    String ITEMS = "cache";
    @Input(ITEMS) GlobalKTable<String, Item> cache();
}

@Data class Item {
    private String key;
    private String value;
}

@Data class ItemList {
    private List<Item> items;
}

public class SampleSerdes {
    public static class ListSerde extends JsonSerde<ItemList> {}
    public static final Serde<ItemList> LIST_SERDE = new ListSerde();

    public static class ItemSerde extends JsonSerde<Item> {}
    public static final Serde<Item> POSITION_SERDE = new ItemSerde();
}
```

Above fails to start when activating the kerberos profile.
