### ISSUE TITLE
Use default consumer-group for multiple bindings

### ISSUE THREAD

**Issue by marbon87** [spring-cloud/spring-cloud-stream-binder-kafka#440]
Hi,

i want to have multiple bindings using KStream-Processors in the same application with the same consumer-group, but then only one bindings is acutally processing.

This is the config from my boot application

```
spring:
  cloud:
    stream:
      default:
        group: ${spring.application.name}
      bindings:
        foo:
          destination: foo
        bar:
          destination: bar

        transformedFoo:
          destination: transformedFoo
        transformedBar:
          destination: transformedBar
```

This is the FooProcessor (Bar looks the same):
```@Component
@RequiredArgsConstructor
@EnableBinding(Foo.Processor.class)
public class Foo {

	@StreamListener(Processor.INPUT)
	@SendTo(Processor.OUTPUT)
	public KStream<?, String> process(KStream<?, String> input) {
		return input;
	}

	public interface Processor {
		String INPUT = "foo";
		String OUTPUT = "transformedFoo";

		@Input(INPUT)
		KStream<?, ?> input();

		@Output(OUTPUT)
		KStream<?, ?> output();
	}

}
```

When i started the application, only messages from foo or bar are processed and send to transformedFoo or transformedBar.

Also i get the following warning:
```
15:17:01 [mThread-1] WARN  o.a.k.c.c.i.ConsumerCoordinator     - [Consumer clientId=my-stream-app-6e9c0f90-132a-4a14-8ed1-bde6fd06a8e3-StreamThread-1-consumer, groupId=my-stream-app] The following subscribed topics are not assigned to any members: [bar]
```

Isn't it possible to use the same consumer group for multiple bindings in the same application?
When i use MessageChannel-Processor it works just fine.
