### ISSUE TITLE
Setting default configuration for all kafka consumers/producers

### ISSUE THREAD

**Issue by lendle** [spring-cloud/spring-cloud-stream-binder-kafka#444]
I'm setting 
```
spring.cloud.stream.kafka.binder.configuration:
    key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    schema.registry.url: http://localhost:8081
```

The `key.serializer` and `value.serializer` configs show up in the configuration map, and the correct class is used for the serializers, when `configure` is called on the serializers, the `schema.registry.url` configuration property is not available. (The `schema.registry.url` property is required for confluent's avro serializers.)

If I use the spring-kafka config`spring.kafka.producer.properties.schema.registry.url: http://localhost:8081`, then everything works as expected.

Maybe unknown properties are filtered out of the configuration map by spring-cloud-stream-kafka?
