### ISSUE TITLE
Consumer Concurrency property has no effect

### ISSUE THREAD

**Issue by titoc** [spring-cloud/spring-cloud-stream-binder-kafka#474]
I configured consumer as per this [https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_configuration_options.html](https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_configuration_options.html)

```
spring-cloud-dependencies:Finchley.SR1
springBootVersion = '2.0.6.RELEASE'
```

There are 4 partitions for my topic and messages are filled in round robin by the producer.
```
root@kafka:/# kafka-run-class kafka.tools.GetOffsetShell --broker-list localhost:9092 --topic kstream_test --time -1
kstream_test:2:222
kstream_test:1:203
kstream_test:3:188
kstream_test:0:278
```
But the consumer concurrency property has no effect.

```
spring.cloud.stream.bindings.input:
  destination: kstream_test
  group: consumer-group-G1_test
  consumer:
    useNativeDecoding: true
    headerMode: raw
    startOffset: latest
    partitioned: true
    concurrency: 3
```
It still runs on 1 thread and not 3. The current work around as per my [SO question](https://stackoverflow.com/questions/52878308/spring-cloud-stream-kstream-consumer-concurrency-has-no-effect/52878849#52878849) is to use the below config.

```
spring.cloud.stream.kafka.streams.binder.configuration:
  num.stream.threads: 3
```

Sample project to reproduce the problem https://github.com/titoc/kstream-demo
