### ISSUE TITLE
Kafka metrics not appearing on Actuator 

### ISSUE THREAD

**Issue by lawhiteley** [spring-cloud/spring-cloud-stream-binder-kafka#498]
Hi,

We're trying to expose our Kafka binder's metrics using Actuator but they don't seem to be appearing. Based on the documentation, we expected `spring.cloud.stream.binder.kafka.offset` to appear in the names array on the `/actuator/metrics` endpoint with details at `/actuator/metrics/spring.cloud.stream.binder.kafka.offset`. We're using version `2.1.0.RELEASE` of Spring Boot and Actuator as well as version `1.1.0` of Micrometer. Our binding is appearing at `/actuator/bindings`. 

Our `application.yml` contains the following: 

```
management:
  endpoints:
    web:
      exposure:
        include: bindings, metrics, health
```

Happy to supply any more information if required.

Thanks
