### ISSUE TITLE
Is it possible to configure multibinder multi kstream application?

### ISSUE THREAD

**Issue by lukaszkrawiec** [spring-cloud/spring-cloud-stream-binder-kafka#632]
Hi all,

I am trying to configure an application that consumes a KStream from one Kafka cluster, and produces a KStream that I want to be written to another Kafka cluster.

What I'm observing is that despite providing a different broker for the output binding, the application is still writing the output Kafka topic to the same broker that it sources the data from. I'm in the process of creating a sample app, but I'm hoping someone can notice a problem with my configs below.

Configuration:
```
spring:
  cloud:
    stream:
      kafka:
        streams:
      bindings:
        input:
          binder: kafka1
          destination: inputTestTopic
          contentType: text/plain
          group: testGroup
        output:
          binder: kafka2
          contentType: text/plain
          destination: outputTestTopic
      binders:
        kafka1:
          type: kstream
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    streams:
                      binder:
                        brokers: localhost:9092
        kafka2:
          type: kstream
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    streams:
                      binder:
                        brokers: localhost:9093
```

And application code
```
@EnableBinding(KafkaStreamsProcessor.class)
@Slf4j
public class StreamEventProcessor {

    @StreamListener("input")
    @SendTo("output")
    public KStream<String, String> process(final KStream<String, String> input) {
        KStream<String, String> kstream = null;
        try {
            kstream =  input
                    .mapValues((k, v) -> {
                        log.info(v);
                        return v.toLowerCase();
                    });

        } catch (Exception exception) {
            log.error("Exception while processing kstream event ", exception);
        }

        return kstream;
    }
}
```

Thanks,
Lukasz
