### ISSUE TITLE
Unable to connect to kafka brokers by ssl

### ISSUE THREAD

**Issue by IvanMikhailenkaEpam** [spring-cloud/spring-cloud-stream-binder-kafka#668]
Hi,
Faced with problem, that I can't connect to my kafka remote broker by SSL

**application.yml**
```
  spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9093
          autoCreateTopics: false
        bindings:
          customers-in:
            destination: customers
            contentType: application/json
          customers-out:
            destination: customers
            contentType: application/json
  kafka:
    ssl:
      protocol: SSL
      trust-store-location: guest.truststore
      trust-store-password: 123456
      key-password: 123456
      key-store-location: guest.keystore
      key-store-password: 123456
````

**pom.xml**

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>kafka-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-kafka</artifactId>
      <version>2.1.2.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
      <version>2.1.2.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream</artifactId>
      <version>2.1.2.RELEASE</version>
    </dependency>
```

Got such **error message**: 

``` 
2019-06-08 14:36:59.863 ERROR 29864 --- [           main] o.s.c.s.b.k.p.KafkaTopicProvisioner      : Failed to obtain partition information

org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

Also can add that my kafka broker works fine and I can connect to it with `spring.boot version: 2.0.1.RELEASE` and `Kafka version: 1.0.1` 
**Old project application.properties**
```
spring.kafka.bootstrap-servers=my-kafka:9093
spring.kafka.consumer.properties.[group.id]=group_23_spring-kafka
        
# SSL
spring.kafka.properties.[security.protocol]=SSL
spring.kafka.ssl.trust-store-location=guest.truststore
spring.kafka.ssl.trust-store-password=123456
spring.kafka.ssl.key-store-password=123456
spring.kafka.ssl.key-store-location=guest.keystore
spring.kafka.ssl.key-password=123456
```
How I have to configure application.yml to be able to connect by SSL?
Thank you

**Comment by garyrussell** [comment]
```yaml
  kafka:
    ssl:
      protocol: SSL
```

Is not the same as `security.protocol`. It is mapped to

```java
    public static final String SSL_PROTOCOL_CONFIG = "ssl.protocol";
    public static final String SSL_PROTOCOL_DOC = "The SSL protocol used to generate the SSLContext. "
            + "Default setting is TLS, which is fine for most cases. "
            + "Allowed values in recent JVMs are TLS, TLSv1.1 and TLSv1.2. SSL, SSLv2 and SSLv3 "
            + "may be supported in older JVMs, but their usage is discouraged due to known security vulnerabilities.";
``` 

You still need to set

```yaml
spring:
   kafka:
     properties:
       security.protocol: ssl
```

**Comment by IvanMikhailenkaEpam** [comment]
Thanks for response
I've updated my a **application.yml**

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9093
          autoCreateTopics: false
        bindings:
          customers-in:
            destination: customers
            contentType: application/json
          customers-out:
            destination: customers
            contentType: application/json

  kafka:
    properties:
      security.protocol: SSL
      ssl:
        endpoint:
          identification:
            algorithm: null
    ssl:
      trust-store-location: guest.truststore
      trust-store-password: 123456
      key-password: 123456
      key-store-location: guest.keystore
      key-store-password: 123456
```
But I still get  **info message and then error** 

```
2019-06-10 17:58:03.597  INFO 30220 --- [| adminclient-1] o.a.k.c.a.i.AdminMetadataManager         : [AdminClient clientId=adminclient-1] Metadata update failed

org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.

2019-06-10 17:59:03.636 ERROR 30220 --- [           main] o.s.c.s.b.k.p.KafkaTopicProvisioner      : Failed to obtain partition information

org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```
