### ISSUE TITLE
Kafka consumer property 'resetOffsets' has no effect

### ISSUE THREAD

**Issue by cmuelhau** [spring-cloud/spring-cloud-stream-binder-kafka#67]
While creating a consumer (and setting group id), the property `spring.cloud.stream.kafka.bindings.<channelName>.consumer.resetOffsets` (as described here: http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/htmlsingle/#_kafka_consumer_properties) seems to have no effect, and consumer consumes from last offset.
Sample properties:
```yaml
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: topic
          group: sample_group
      kafka:
        bindings:
          input:
            consumer:
              resetOffsets: true
              startOffset: earliest
```
The `KafkaConsumerProperties#resetOffsets` extension is set to true, but it doesn't seem to trigger any specific resetting of offsets.
