### ISSUE TITLE
(Global)KTableBinderConfiguration cannot find KafkaProperties when using multi-binder configuration 

### ISSUE THREAD

**Issue by iamdaniu** [spring-cloud/spring-cloud-stream-binder-kafka#681]
When creating a binder of type `ktable` or `globalktable`, adding an `environment` configuration property results in "NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' available".

This is analogue to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/411 - where the `kstream` binder was fixed. However, `ktable` and `globalktable` binder types are still broken.

Code to reproduce:
```
@EnableBinding(CacheBinding.class)
public class ItemCacher {
    @StreamListener
    void materialize(@Input(CacheBinding.ITEMS) KTable<String, Item> items) {}

    public static class ItemSerde extends JsonSerde<Item> {}
    public static final Serde<Item> POSITION_SERDE = new ItemSerde();
}

interface CacheBinding {
    String ITEMS = "cache";
    @Input(ITEMS)
    KTable<String, Item> cache();
}

@Data class Item {
    private String key;
    private String value;
}
```

`application.yml`:
```
spring.cloud.stream:
  bindings.cache:
    destination: items-topic
    binder: cache
    group: cache-group
  kafka.streams:
    binder:
      application-id: cacher
      brokers: localhost:9092
      configuration:
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: com.example.minfail.ItemCacher$ItemSerde
    bindings.consumer:
      applicationId: cache
      materializedAs: items-cache
  binders.cache:
    type: ktable
    environment:
      security.protocol: SASL_SSL
```
Removing the `environment` section below the `cache`-binder results in the application starting up fine.

Changing the binder type to `globalktable` (and adjusting the binding types in the Java code) also results in the problem.

Changing binder type to `kstream` works fine.
