### ISSUE TITLE
Topic provisioning for producers ignores topic.properties settings

### ISSUE THREAD

**Issue by pzieminski** [spring-cloud/spring-cloud-stream-binder-kafka#684]
Using application configuration as follows

```
spring:
  cloud:
    stream:
      bindings:
        myoutput:
          destination: output-topic
        myinput:
          destination: input-topic
          group: mygroup

      kafka:
        streams:
          binder:
            brokers: docker-machine:9092
            autoCreateTopics: true
            minPartitionCount: 4
            configuration:
              state.dir: ${java.io.tmpdir}/kafka-streams
              commit.interval.ms: 3000
              producer.compression.type: snappy
              application.id: hello-world

          bindings:
            myoutput:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue1.JsonNodeSerde
                topic.properties:
                  cleanup.policy: compact
            myinput:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue1.JsonNodeSerde
                topic.properties:
                  cleanup.policy: compact
```
and bindings
```
public interface Bindings {

    String MYINPUT = "myinput";
    String MYOUTPUT = "myoutput";

    @Input(MYINPUT)
    KStream<String, JsonNode> input();

    @Output(MYOUTPUT)
    KStream<String, JsonNode> output();
}
```

Causes both topics output-topic and input-topic to be created, but only the consumer topic has its properties set (in this case cleanup.policy), while the producer properties are ignored.

I've debugged the binder code and the provisioning of topics for producers seems to always use empty properties. See `org.springframework.cloud.stream.binder.kafka.streams.KStreamBinder#doBindProducer`. `extendedProducerProperties` below are created in place and never populated with anything.
This is 2.1.2.RELEASE but 2.2.0.RELEASE looks the same.

```
	@Override
	@SuppressWarnings("unchecked")
	protected Binding<KStream<Object, Object>> doBindProducer(String name, KStream<Object, Object> outboundBindTarget,
															ExtendedProducerProperties<KafkaStreamsProducerProperties> properties) {
		ExtendedProducerProperties<KafkaProducerProperties> extendedProducerProperties = new ExtendedProducerProperties<>(
				new KafkaProducerProperties());
		this.kafkaTopicProvisioner.provisionProducerDestination(name, extendedProducerProperties);
		Serde<?> keySerde = this.keyValueSerdeResolver.getOuboundKeySerde(properties.getExtension());
		Serde<?> valueSerde = this.keyValueSerdeResolver.getOutboundValueSerde(properties, properties.getExtension());
		to(properties.isUseNativeEncoding(), name, outboundBindTarget, (Serde<Object>) keySerde, (Serde<Object>) valueSerde);
		return new DefaultBinding<>(name, null, outboundBindTarget, null);
	}
```
