### ISSUE TITLE
Topic provisioning for consumers ignores topic.properties settings if binding type is KTable or GlobalKTable

### ISSUE THREAD

**Issue by pzieminski** [spring-cloud/spring-cloud-stream-binder-kafka#687]
Using application configuration as follows

```
spring:
  cloud:
    stream:
      bindings:
        input1:
          destination: input1-topic
          group: mygroup
        input2:
          destination: input2-topic
          group: mygroup
        input3:
          destination: input3-topic
          group: mygroup

      kafka:
        streams:
          binder:
            brokers: docker-machine:9092
            autoCreateTopics: true
            minPartitionCount: 4
            configuration:
              state.dir: ${java.io.tmpdir}/kafka-streams
              commit.interval.ms: 3000
              producer.compression.type: snappy
              application.id: hello-world

          bindings:
            input1:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue2.JsonNodeSerde
                topic.properties:
                  cleanup.policy: compact
            input2:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue2.JsonNodeSerde
                materializedAs: input2-table
                topic.properties:
                  cleanup.policy: compact
            input3:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue2.JsonNodeSerde
                materializedAs: input3-global
                topic.properties:
                  cleanup.policy: compact
```
and binding configuration for the 3 consumers above
```
public interface Bindings {

    String INPUT1 = "input1";
    String INPUT2 = "input2";
    String INPUT3 = "input3";

    @Input(INPUT1)
    KStream<String, JsonNode> input1();

    @Input(INPUT2)
    KTable<String, JsonNode> input2();

    @Input(INPUT3)
    GlobalKTable<String, JsonNode> input3();
}
```
Causes all 3 topics to be created, but only input1-topic properties are set as expected. input2-topic and input3-topic have no properties set.
