### ISSUE TITLE
spring.cloud.stream.bindings.<channelName>.group not work, can you help me ?

### ISSUE THREAD

**Issue by naxienianHaiF** [spring-cloud/spring-cloud-stream-binder-kafka#710]
[ https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR3/reference/htmlsingle/ .](url)
I setted `spring.cloud.stream.bindings.<channelName>.group` to the channel,    but it not work.   I have three consumers, but three consumes resolve the same message. 

```
spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost
                    zk-nodes: localhost
                bindings:
                    scoreProcessChannel:
                        consumer:
                            configuration:
                                max.poll.interval.ms: 600000
                                max.poll.records: 30
            bindings:
                scoreProcessChannel:
                    group: score-consume-group
                    destination: score-process-applet-test`


    @StreamListener(ScoreProcessChannel.CHANNEL)
    public void consume(String string){}`

    @StreamListener(ScoreProcessChannel.CHANNEL)
    public void consume(String string){}`

    @StreamListener(ScoreProcessChannel.CHANNEL)
    public void consume(String string){}`
```
