### ISSUE TITLE
Naming kstreams binder causes startup failure if a consumer binding of type GlobalKTable is used

### ISSUE THREAD

**Issue by pzieminski** [spring-cloud/spring-cloud-stream-binder-kafka#767]
I've created a sample application demonstrating the issue here
https://github.com/pzieminski/kafka-binder-issue1

I tried configuring a multi-binder scenario involving a kstreams and kafka binders similar to the configuration shown here
https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-kafka-streams

However, the application fails to start the moment I add naming of the kstreams binder. The sample application shows the two scenario. Please take a look at the attached readme.

In short this configuration and bindings work
```
spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              commit.interval.ms: 3000
              state.dir: ${java.io.tmpdir}/kafka-streams

---

spring.profiles: foo

spring:
  cloud:
    stream:

      bindings:
        foo-output:
          destination: foo-output-topic
        foo-input:
          destination: foo-input-topic
          group: foo-group

      kafka:
        streams:
          bindings:
            foo-output:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact
            foo-input:
              consumer:
                applicationId: foo-app
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact

---
spring.profiles: baz

spring:
  cloud:
    stream:

      bindings:
        baz-output:
          destination: baz-output-topic
        baz-input:
          destination: baz-input-topic
          group: baz-group
        baz-global-input:
          destination: foo-output-topic
          group: baz-group

      kafka:
        streams:
          bindings:
            baz-output:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact
            baz-input:
              consumer:
                applicationId: baz-app
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact
            baz-global-input:
              consumer:
                applicationId: baz-app
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                materializedAs: baz-global
                topic.properties:
                  cleanup.policy: compact

```

```
    public interface Bindings {

        String INPUT = "baz-input";
        String GLOBAL_INPUT = "baz-global-input";
        String OUTPUT = "baz-output";

        @Input(INPUT)
        KStream<String, String> input();

        @Input(GLOBAL_INPUT)
        GlobalKTable<String, String> globalInput();

        @Output(OUTPUT)
        KStream<String, String> output();
    }
```

But as soon as I name the binder like so (kafka1 in this case)
```
spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              commit.interval.ms: 3000
              state.dir: ${java.io.tmpdir}/kafka-streams
      binders:
        kafka1:
          type: kstream

---
spring.profiles: foo

spring:
  cloud:
    stream:

      bindings:
        foo-output:
          destination: foo-output-topic
          binder: kafka1
        foo-input:
          destination: foo-input-topic
          group: foo-group
          binder: kafka1

      kafka:
        streams:
          bindings:
            foo-output:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact
            foo-input:
              consumer:
                applicationId: foo-app
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact

---
spring.profiles: baz

spring:
  cloud:
    stream:

      bindings:
        baz-output:
          destination: baz-output-topic
          binder: kafka1
        baz-input:
          destination: baz-input-topic
          group: baz-group
          binder: kafka1
        baz-global-input:
          destination: foo-output-topic
          group: baz-group
          binder: kafka1

      kafka:
        streams:
          bindings:
            baz-output:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact
            baz-input:
              consumer:
                applicationId: baz-app
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                topic.properties:
                  cleanup.policy: compact
            baz-global-input:
              consumer:
                applicationId: baz-app
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                materializedAs: baz-global
                topic.properties:
                  cleanup.policy: compact
```

the start-up fails with the following exception
```
Caused by: java.lang.IllegalStateException: The binder 'kafka1' cannot bind a com.sun.proxy.$Proxy68
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:194) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:130) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:337) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:92) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:254) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_181]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 12 common frames omitted
```

Removing the GlobalKTable typed binding allows it to start even with the binder named.

Hope this very convoluted scenario is made clear by the sample I provided.

**Comment by pzieminski** [comment]
Is there a sample anywhere that demonstrates how to achieve a multi-binder scenario with kstreams and kafka binder involving a global table consumer?

**Comment by sobychacko** [comment]
@pzieminski Sorry for not getting back to you earlier. We will take a look soon. Thank you for the detailed report on this.

**Comment by sobychacko** [comment]
@pzieminski I think the problem is that you are trying to use a `KStream` binder for a `GlobalKTable` binding. When I changed the configs as below, I can start the app with the failing profile.

```
spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              commit.interval.ms: 3000
              state.dir: ${java.io.tmpdir}/kafka-streams
      binders:
        kafka1:
          type: kstream
        global-input:
          type: globalktable
```
and then
```
spring.profiles: baz_fail

spring:
  cloud:
    stream:

      bindings:
        baz-output:
          destination: baz-output-topic
          binder: kafka1
        baz-input:
          destination: baz-input-topic
          group: baz-group
          binder: kafka1
        baz-global-input:
          destination: foo-output-topic
          group: baz-group
          binder: global-input
...
```
Please confirm that it works on your end after making these changes. I agree that the docs on this matter are not very clear. We will use this as an issue for improving the docs.  
For `KStream` bindings, you need to use a binder of type `KStream`, for `KTable` bindings, the binder type is `ktable` and `GlobalKTable` bindings, it is `globalktable`.
