### ISSUE TITLE
Consumer pause & resume not working with multiple Kafka binders

### ISSUE THREAD

**Issue by s-sathish** [spring-cloud/spring-cloud-stream-binder-kafka#770]
https://github.com/s-sathish/SampleKafkaProducerConsumer

I have a sample Kafka producer consumer application in Spring boot, cloud stream (Above link)

**Scenario**:

- Multiple Kafka binders: Different zookeeper/Kafka broker
     kafka1 - zkNode = localhost:2181, broker = localhost:9092
     kafka2 - zkNode = localhost:2182, broker = localhost:9093

- Producer produces a message to consumer

- Consumer(autoCommitOffset = false, relying on manual ack) receives the message

- Intentionally fail the processing logic and putting the message to two DLQ's

- Each DLQ consumer have different idleEventInterval

- On first message posting, the processing logic fails intentionally and then the message goes to DLQ. The DLQ's receives the message. Till this point everything is working fine.

- After this, **the consumer pause & resume logic doesn't seems to be working**
```
consumer.pause(Collections.singleton(new TopicPartition(TOPIC, PARTITION)));

@Bean
public ApplicationListener<ListenerContainerIdleEvent> wakingUpAllDLQConsumerAsPerRetryLogic() {
    return event -> {
        if (event.getConsumer().paused().size() > 0) {
            event.getConsumer().resume(event.getConsumer().paused());
        }
    };
}
```

**Spring cloud stream version**: "Greenwich.RELEASE"

**Comment by s-sathish** [comment]
Hi @olegz 

Following is the application properties:
```
spring:
  cloud:
    stream:
      bindings:
        in:
          destination: producer-consumer-topic
          group: producer-consumer-group
          binder: kafka1
        out:
          destination: producer-consumer-topic
          binder: kafka1
        dlq-out-1:
          destination: producer-consumer-topic-dlq-1
          binder: kafka2
        dlq-out-2:
          destination: producer-consumer-topic-dlq-2
          binder: kafka2
        dlq-in-1:
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq
          binder: kafka2
        dlq-in-2:
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq
          binder: kafka2
      binders:
        kafka1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
        kafka2:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9093
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2182
      kafka:
        binder:
          health-timeout: 60
        bindings:
          in:
            consumer:
              autoCommitOffset: false
          dlq-in-1:
            consumer:
              idleEventInterval: 10000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
          dlq-in-2:
            consumer:
              idleEventInterval: 15000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
```
As you can see,

- I'm having multiple Kafka binders (kafka1, kafka2). Some topics gets registered to kafka1 binder and other topics gets registered to kafka binder2

- For two consumers, I've set the bindings property "idleEventInterval", so that I can try out the consumer.pause() & consumer.resume() functionalities as below

```
@StreamListener(value = Stream.DLQ_CONSUME_1)
public void messageConsumer1DLQ(@Valid Message<ConsumerData> consumerData, @Header(KafkaHeaders.CONSUMER) Consumer<?, ?> consumer) {
    log.info("DLQ 1 message consumer Info = {}", consumer);

    log.info("Received(From DLQ 1) message event in consumer, message = {}", consumerData);

    consumer.pause(Collections.singleton(new TopicPartition(DLQ_TOPIC_NAME_1, DLQ_TOPIC_PARTITION)));
}

@StreamListener(value = Stream.DLQ_CONSUME_2)
public void messageConsumer2DLQ(@Valid Message<ConsumerData> consumerData, @Header(KafkaHeaders.CONSUMER) Consumer<?, ?> consumer) {
    log.info("DLQ 2 message consumer Info = {}", consumer);

    log.info("Received(From DLQ 2) message event in consumer, message = {}", consumerData);

    consumer.pause(Collections.singleton(new TopicPartition(DLQ_TOPIC_NAME_2, DLQ_TOPIC_PARTITION)));
}
    
@Bean
public ApplicationListener<ListenerContainerIdleEvent> wakingUpAllDLQConsumerAsPerRetryLogic() {
    return event -> {
        Collection<TopicPartition> topicPartitions = event.getTopicPartitions();
        for(TopicPartition topicPartition : topicPartitions) {
            if(topicPartition.toString().equals(DLQ_TOPIC_NAME_1_PARTITION)
                    || topicPartition.toString().equals(DLQ_TOPIC_NAME_2_PARTITION)) {
                log.info("Resuming the DLQ Consumers as per each topic logic's, event = {}", event);

                if(event.getConsumer().paused().size() > 0) {
                    log.info("Found new events in DLQ. Waking up and gonna process the messages...");
                    event.getConsumer().resume(event.getConsumer().paused());
                } else {
                    log.info("No new events posted to DLQ. Gonna sleep again ZZZ...");
                }
            }
        }
    };
}
```

So, once the above two consumer receives the message, it is supposed to go into paused state and then resume as per the "idleEventInterval" property set for each consumer, But none of the pause or resume events seems to be happening.

Let me know if the above explanation makes it clear.

**Comment by s-sathish** [comment]
Now I tried the following scenario - Just a **single named Kafka binder**. Below is the application properties
```
spring:
  cloud:
    stream:
      bindings:
        in:
          destination: producer-consumer-topic
          group: producer-consumer-group
          binder: kafka1
        out:
          destination: producer-consumer-topic
          binder: kafka1
        dlq-out-1:
          destination: producer-consumer-topic-dlq-1
          binder: kafka1
        dlq-out-2:
          destination: producer-consumer-topic-dlq-2
          binder: kafka1
        dlq-in-1:
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq
          binder: kafka1
        dlq-in-2:
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq
          binder: kafka1
      binders:
        kafka1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
      kafka:
        bindings:
          in:
            consumer:
              autoCommitOffset: false
          dlq-in-1:
            consumer:
              idleEventInterval: 10000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
          dlq-in-2:
            consumer:
              idleEventInterval: 15000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error

logging:
  level:
    org.springframework.integration: DEBUG
```

So, even with single named Kafka binder, the consumer pause/resume events doesn't seems to be happening.
And once I stop my application, I can see the following **WARN** messages in the logs as part of the shutdown process -
```
2019-10-17 12:02:34.394  WARN 3294 --- [       Thread-8] o.s.cloud.stream.binding.BindingService  : Trying to unbind 'in', but no binding found.
2019-10-17 12:02:34.404  WARN 3294 --- [      Thread-11] o.s.cloud.stream.binding.BindingService  : Trying to unbind 'dlq-in-1', but no binding found.
2019-10-17 12:02:34.404  WARN 3294 --- [      Thread-11] o.s.cloud.stream.binding.BindingService  : Trying to unbind 'dlq-in-2', but no binding found.
```

Looks like the consumer properties bindings itself haven't happened at first place.

**Comment by sobychacko** [comment]
@s-sathish if you comment out this section below, I think it starts to work (provided that you have Kafka running on the default ports locally)

```
binders:
        kafka1:
          type: kafka
#          environment:
#            spring.cloud.stream.kafka.binder.brokers: localhost:9092
#            spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
 ```

This indicates that somewhere along the chain, the multi binder environment properties are not carried forward. We will investigate further.

**Comment by s-sathish** [comment]
@sobychacko Yeah, Commenting out the part that you suggested made it work for "single named Kafka binder" - consumer pause(), resume() events are working properly now.

Yes, Looks like the problem is with - 
Named Kafka binder environment properties being not processed correctly in the flow.

I think if the binder environment properties is carried forward correctly, then the same should work for multiple named binders as well.

**Comment by sobychacko** [comment]
@s-sathish I spent some time on it with @artembilan and he was able to identify the problem. The issue is that when you have a multi binder scenario (or binder context initialized through a custom environment), the application listener bean is not visible to the binder context as this is only available in the parent context. When you have a custom environment, `SCSt` does not propagate beans from the parent context into the binder context. In order to get around this, you have to explicitly add the configuration class to the binder context in your application's configuration. I changed your settings as below and I am seeing that pause/resume is working. Can you confirm if it addresses your issues?

```
spring:
  cloud:
    stream:
      bindings:
        in:
          destination: producer-consumer-topic
          group: producer-consumer-group
          binder: kafka1
        out:
          destination: producer-consumer-topic
          binder: kafka1
        dlq-out-1:
          destination: producer-consumer-topic-dlq-1
          binder: kafka2
        dlq-out-2:
          destination: producer-consumer-topic-dlq-2
          binder: kafka2
        dlq-in-1:
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq
          binder: kafka2
        dlq-in-2:
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq
          binder: kafka2
      binders:
        kafka1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.main.sources: com.sathish.KPC.consumer.DLQConsumer
        kafka2:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.main.sources: com.sathish.KPC.consumer.DLQConsumer
```
