### ISSUE TITLE
Kafka Streams binder not scanning properties from multi binder configuration

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#815]
Given the example configuration provided below, the first binder configuration from the multi binder environment is overwritten by the second configuration.

```
spring:
  cloud:
    stream:
      bindings:
        firstKStreamOut:
          destination: test_demo_first_aggregated_topic
          binder: kafka1
        firstKStreamIn:
          destination: test_demo_first_inbound
          group: test_demo_first_inbound_group
          binder: kafka1
        secondKStreamOut:
          destination: test_demo_second_aggregated_topic
          binder: kafka2
        secondKStreamIn:
          destination: test_demo_second_inbound
          group: test_demo_second_inbound_group
          binder: kafka2
      binders:
        kafka1:
          type: kstream
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    streams:
                      binder:
                        application-id: ID1
                        autoAddPartitions: true
                        minPartitionCount: 3
                        replicationFactor: 1
                        serdeError: logAndContinue
                        brokers: localhost:9092
                        configuration:
                          acks: all
                          compression.type: gzip
                          max.request.size: 104857600
                          cache.max.bytes.buffering: 104857600
                          commit.interval.ms: 10000
                          windowstore.changelog.additional.retention.ms: 76400000
                          processing.guarantee: exactly_once
                          replication.factor: 1
                          default:
                            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        kafka2:
          type: kstream
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    streams:
                      binder:
                        application-id: ID2
                        autoAddPartitions: true
                        minPartitionCount: 3
                        replicationFactor: 1
                        serdeError: logAndContinue
                        brokers: localhost:9092
                        configuration:
                          acks: all
                          compression.type: gzip
                          max.request.size: 104857600
                          cache.max.bytes.buffering: 104857400
                          commit.interval.ms: 20000
                          windowstore.changelog.additional.retention.ms: 66400000
                          processing.guarantee: exactly_once
                          replication.factor: 1
                          default:
                            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
```
