### ISSUE TITLE
Kafka Streams same input and output destination causes already defined error

### ISSUE THREAD

**Issue by vitjouda** [spring-cloud/spring-cloud-stream-binder-kafka#841]
When I define Function with same input and output bindings, I get `bean with that name has already been defined`. Using `spring-cloud Hoxton.SR1`.

application.yml
```
spring:
  cloud:
    stream:
      function:
        definition: eventStream
        bindings:
          eventStream-in-0:
            destination: events-topic
          eventStream-out-0:
            destination: events-topic
```
```
@Bean
public Function<KStream<UUID, Event>, KStream<UUID, Event>> eventStream() {
        return kStream -> kStream
                .map(...);
}
```

**Comment by sobychacko** [comment]
@vitjouda What is your use case? What is the motivation behind using the same destination for input and output on the same processor? That will most likely generate an endless cycle. In any case, it is not clear why you are getting that exception. If you can share a small sample, we can look further.

**Comment by vitjouda** [comment]
@sobychacko We were implementing simple Saga pattern with orchestrator and decided to use one topic for multiple types of messages to ensure sequential processing for all participants in case of failure or lags if it were on multiple topics. Orchestrator logic handles state transitions and ignores whatever might cause any cycles. Clients simple never listen or ignore response types so they never cycle. We bypassed this using `.to` operator for the moment.

I still think this should work because @StreamListener based handlers can achieve this binding. I will provide simple example as soon as I have some spare time.

**Comment by sobychacko** [comment]
@vitjouda Apologies for the delay in getting back to you. I was finally able to run through this issue. I think your issue is a configuration issue. The correct yaml should be this:

```
spring:
  cloud:
    stream:
      function:
        definition: eventStream
    bindings:
      eventStream-in-0:
        destination: events-topic
      eventStream-out-0:
        destination: events-topic
```

Notice that your original configuration had `bindings` provided at a different level. Here is your original config:
```
spring:
  cloud:
    stream:
      function:
        definition: eventStream
        bindings:
          eventStream-in-0:
            destination: events-topic
          eventStream-out-0:
            destination: events-topic
```
Here, `bindings` are provided under `function`, not under `stream`.  While this works, it has a different semantic meaning. You should use, `spring.cloud.stream.function.bindings.eventStream-in-0` or `spring.cloud.stream.function.bindings.eventStream-out-0`,  in order to change the actual binding name. When you use this, you should provide all the binding level properties on those overridden binding names. This feature of overriding binding names was added into Spring Cloud Stream to provide more expressive (domain-specific) binding names rather than using the default `functionName-[in][out]-n` naming.

With your original config, the following should work.

```
spring:
          cloud:
            stream:
              function:
                definition: eventStream
                bindings:
                  eventStream-in-0: my-input
                  eventStream-out-0: my-output
              bindings:
                my-input:
                  destination: events-topic
                my-output:
                  destination: events-topic
```
Please let me know if it works with the changes I suggested. Thank you!
