### ISSUE TITLE
Kafka Asynchronous Producer Message Time Out Exception

### ISSUE THREAD

**Issue by rajjav123** [spring-cloud/spring-cloud-stream-binder-kafka#847]
Hi ,

We have a Springboot application that uses spring-cloud-stream-binder-kafka to send messages to a Kafka Topic .We are sending the message in Synchronous mode .We are using Synchronous mode because we want to do  some action when an error comes during message sending .This has been working fine for a while. We even did a load testing with 100k messages in a hour and we never got any TimeOut Exception .But recently ,we are seeing some timeout exceptions .The time out is mainly happening when we send a single message .The interesting thing is even though we are getting a TimeOut exception , the message is still reaching Kafka Topic . Once we get a timeout exception , the next set of messages are going through without any time out . There is no consistency in the Timeout exception . Please help me to understand what exactly is happening here.

Code : 

```java
@Service
@EnableBinding(Source.class)
{
try
{
   source .output().send(MessageBuilder.withPayLoad(JsonStringMessage).build();
}
catch(MessageTimeOutException ex)
{
log.error("Kafka MessageTimeOut");
}
}
```

application .yml : 

```yaml
 spring:
    cloud: 
     stream:
      binders: 
       kafka1:
        type: Kafka
        environment: 
         spring: 
          cloud: 
           stream: 
            kafka:
             binder:
               brokers: broker name
               configuration: 
                  sasl.jass.config: kafkaconnectionstring
                  ssl.mechanism: PLAIN
                  security.protocol: SASL_SSL
                  retries: 3
             bindings:
              output:
               producer: 
                sync:true
      bindings:
        output: 
          binder: kafka1
          destination: Kafka topic name
```

 

Springboot Version : 2.1.5
Spring-cloud-stream-binder-kafka : 2.1.2

Exception details : 

org.springframework.integration.MessageTimeOutException: Timeout waiting for response from Kafkaproducer; nested exception is java.util.concurrent.TimeoutException

Regards,
Rajeev
