### ISSUE TITLE
Multiple ApplicationIds Issue

### ISSUE THREAD

**Issue by sumitbaurai** [spring-cloud/spring-cloud-stream-binder-kafka#857]
Hi, 

I have two StreamListeners in my Kafka Streams Spring boot application. As instructed in the reference Guide, I configured the two stream listeners to have their own application id's as follows

```
          bindings:
            sLiqFfdEventInput:
              applicationId: lendx-liq-flexfield-mapper-clone-to-data-topic-tester
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
            tlsObjExtAttributes:
              applicationId: lendx-liq-flexfield-mapper-tester-12
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
```
However, the application.id's that I can see assigned are :
```
application.id = lendx-liq-flexfield-mapper-12 -- this is the same as the spring application name
application.id = FlexFieldMapper-clone-applicationId - this is a concatenation of ClassName-streamListener-method-applicationId
```

My spring.cloud.version is Hoxton.SR1

I had to override the spring-cloud-stream-binder-kafka-streams (due to an issue with the 3.0.1Release that i dont rcall now)

```
<spring.cloud.version>Hoxton.SR1</spring.cloud.version>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
            <version>3.0.0.RELEASE</version>
        </dependency>
```

**Comment by sobychacko** [comment]
@sumitbaurai Can you share your full config and the stream listeners for us to further look into this? I am not sure if there are some kind of issues with your config. In the meantime, did you try upgrading to the latest functional model? Also, since you are on `Hoxton`, I suggest using the latest SR.

**Comment by sumitbaurai** [comment]
Apologies.. got stuck in other issues so could not provide an update.... Please find application.yml and the streamlisterner method signatures below. 

Also attached the pom

However, I still see the following message in my logs :
```

[2020-03-04 16:53:37,283] INFO Binder Generated Kafka Streams Application ID: FlexFieldMapper-process-applicationId (org.springframework.cloud.stream.binder.kafka.streams.AbstractKafkaStreamsBinderProcessor)
[2020-03-04 16:53:37,283] INFO Use the binder generated application ID only for development and testing.  (org.springframework.cloud.stream.binder.kafka.streams.AbstractKafkaStreamsBinderProcessor)
[2020-03-04 16:53:37,283] INFO For production deployments, please consider explicitly setting an application ID using a configuration property. (org.springframework.cloud.stream.binder.kafka.streams.AbstractKafkaStreamsBinderProcessor)
[2020-03-04 16:53:37,283] INFO The generated applicationID is static and will be preserved over application restarts. (org.springframework.cloud.stream.binder.kafka.streams.AbstractKafkaStreamsBinderProcessor)

```

Application.yml

```
spring:
  kafka:
    streams:
      properties:
        group.id: lendx-liq-flexfield-mapper-group-12
        auto.offset.reset: earliest
        processing.guarantee: exactly_once
        schema.registry.url: http://clrv0000156422.ic.ing.net:8081
        replication.factor: 3
        metrics.recording.level: DEBUG
#      application-id: lendx-liq-flexfield-mapper-tester-12
      state-dir: "C:\\ls\\temp\\streams-state"
      client-id: lendx-liq-flexfield-mapper-tester-12
    bootstrap-servers: clrv0000156425.ic.ing.net:9092
  cloud:
    stream:
      default:
        consumer:
          useNativeDecoding: true
        producer:
          useNativeEncoding: true
      schema-registry-client:
        endpoint: http://clrv0000156422.ic.ing.net:8081
      bindings:
        tlsTableExt:
          contentType: application/*+avro
          destination: wbls-liq_cdc-event-lsuser-tls_table_ext
        tlsObjExtAttributes:
          contentType: application/*+avro
          destination: wbls-liq_cdc-event-lsuser-tls_obj_ext_atr
        hFlexFieldSelection:
          contentType: application/*+avro
          destination: wbls-lendx-H_FLEX_FIELD_SELECTION
        tlsMisCode:
          contentType: application/*+avro
          destination: wbls-liq_cdc-event-lsuser-tls_mis_code
        sLiqFfdEventOutput:
          contentType: application/*+avro
          destination: wbls-liq_lendx-event-s_liq_ffd
#        sLiqFfdDataOutput:
#          contentType: application/*+avro
#          destination: wbls-liq_lendx-data-s_liq_ffd
        tlsFamGlobal2:
          contentType: application/*+avro
          destination: wbls-liq_cdc-event-lsuser-tls_fam_global2
        filteredTlsFamGlobal2:
          contentType: application/*+avro
          destination: wbls-liq_lendx-data-tls_fam_global2
      kafka:
        streams:
          binder:
            configuration:
              security:
                protocol: SASL_PLAINTEXT
              sasl:
                mechanism: SCRAM-SHA-256
                jaas:
                  config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="confluent";
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#                applicationId: lendx-liq-flexfield-mapper-tester-12
            brokers: clrv0000156425.ic.ing.net:9092
            replication-factor: 3
          bindings:
            tlsObjExtAttributes:
              applicationId: lendx-liq-flexfield-mapper-tester-13
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
            tlsTableExt:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
            tlsMisCode:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
            hFlexFieldSelection:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
#            sLiqFfdDataOutput:
#              producer:
#                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            sLiqFfdEventOutput:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            tlsFamGlobal2:
              applicationId: tls-global-fam-filter-app-tester-1
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest
            filteredTlsFamGlobal2:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                startOffset: earliest

  application:
    name: lendx-liq-flexfield-mapper-14
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    binders:
      enabled: true
logging:
  level:
    org.springframework: INFO
    com.ing.loaniq2ods: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  #  file: "C:\\ls\\Work\\temp\\${spring.application.name}.log"
  file:
    name: "C:\\ls\\Work\\temp\\${spring.application.name}.log"
#    name: "/opt/logs/streams/${spring.application.name}.log"
#    name: "C:\\ls\\Work\\temp\\${spring.application.name}.log"
##    name: "/opt/logs/streams/${spring.application.name}.log"
#    max-size: 2MB
#    max-history: 3
server:
  port: 10080

```

Stream Listener Methods: 
```

    @StreamListener
    @SendTo("filteredTlsFamGlobal2")
    @SuppressWarnings("unchecked")
    public KStream<String, TLS_FAM_GLOBAL2> filterTlsFamGlobal(@Input("tlsFamGlobal2") KStream<String, TLS_FAM_GLOBAL2> tlsFamGlobalInput) {

   @StreamListener
    @SendTo("sLiqFfdEventOutput")
    @SuppressWarnings("unchecked")
    public KStream<String, S_LIQ_FFD> process(@Input("tlsObjExtAttributes") KStream<String, TLS_OBJ_EXT_ATR> objectAttributeInput,
                                              @Input("tlsTableExt") KStream<String, TLS_TABLE_EXT> tlsTableExtInput,
                                              @Input("tlsMisCode") KStream<String, TLS_MIS_CODE> tlsMisCodeInput,
                                              @Input("hFlexFieldSelection") KStream<String, h_flex_field_selection> flexFieldInput) {
[pom.txt](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4288297/pom.txt)

```

**Comment by sobychacko** [comment]
@sumitbaurai When you have `StreamListener` based processors and want to set `applicationId` per processor, you need to use the `consumer` prefix on the first input binding of the processor. 
For e.g, this should work:
```
bindings:
   tlsObjExtAttributes:
        consumer:
             applicationId: lendx-liq-flexfield-mapper-tester-13
             ....
```
Notice that `applicationId` is after `consumer`.  In your configuration, that is not how it is. Please update your configuration and try again. Ping here if that works so that we can close this issue.
