### ISSUE TITLE
Using DLQ in Spring Cloud Stream Binder Kafka does not commit offsets

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-stream-binder-kafka#870]
Based on the Spring Cloud Stream Binder Kafka documentation:
>autoCommitOnError
Effective only if autoCommitOffset is set to true. If set to false it suppresses auto-commits for messages that result in errors, and will commit only for successful messages, allows a stream to automatically replay from the last successfully processed message, in case of persistent failures. If set to true, it will always auto-commit (if auto-commit is enabled). If not set (default), it effectively has the same value as enableDlq, auto-committing erroneous messages if they are sent to a DLQ, and not committing them otherwise.
Default: not set.

I interpret this as, if my `@StreamListener` runs into an error, it will retry up to `max-attempts` then write to DLQ.
Once the record is sent to DLQ, the offset should be committed. However, when I check the consumer group offset `$ kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group my-consumer-group --describe`, the current offset is not incremented.

This is my application configuration
```
spring:
  cloud:
    stream:
      default:
        group: my-consumer-group
      kafka:
        binder:
          brokers:
            - 127.0.0.1:9092
          producer-properties:
            retries: 2147483647
        bindings:
          input:
            consumer:
              auto-commit-offset: false
              autoCommitOnError: true # by default it it same as enableDlq
              enableDlq: true
              dlqName: test-dlq
              configuration:
                max.poll.interval.ms: 5000
      bindings:
        input:
          destination: test-topic
        output:
          destination: test-topic
```

My StreamListener is similar to below:
I made an error case on purpose to see how DLQ and acks are handled.
```
@EnableBinding(SinkBinding.class)
public class KafkaConsumer {

    @StreamListener(value = SinkBinding.INPUT)
    public void listen(Message<String> message) throws InterruptedException {
        System.out.println("log this message : " + message.getPayload() + " offset : " + message.getHeaders().get(KafkaHeaders.OFFSET).toString());

        String a = null;
        a.substring(0, 3); // causing null pointer exception for testing purposes
        sendAck(message);
    }

    public void sendAck(Message<String> message) {
        Acknowledgment acknowledgment = message.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class);
        if (acknowledgment != null)  {
            try {
                acknowledgment.acknowledge();
                System.out.println("manual commit complete");
            }
            catch (Exception e)  {
                throw e; // retry
            }
        }
    }
}
```

Versions are
spring-boot: 2.2.5.RELEASE
spring-cloud: Hoxton.SR3

These are my test caes and observations
1. Start Kafka consumer app and send a record. Then it will try to process it three times and then fail. Then it is sent to DLQ. At this point, conusmer is idle (nothing happens). However, checking with `kafka-consumer-group` command, the offset is not increased.
2. Before starting the consumer app, send a few records. Then, start the consumer app. It will go through each record and send to DLQ. It should stop here like the first test case. However, once it iterates over all the records, it will go back to the starting offset and write it to DLQ again and again (it loops). When testing with 3 different records, I saw my DLQ was being loaded with those 3 records repeatedly.

Both caes would be handled properly if the offset was being committed correctly with DLQ.

Is this a desired behavior? To me it seems like a bug.
Please let me know.

Thanks,

Jay

**Comment by sobychacko** [comment]
@jskim1991 Couple of observations. In the following `StreamListener`, the `sendAck` method is never called since the NPE is thrown before that. Thus your manual ack is never invoked.
```
@StreamListener(value = SinkBinding.INPUT)
public void listen(Message<String> message) throws InterruptedException {
      System.out.println("log this message : " + message.getPayload() + " offset : " + message.getHeaders().get(KafkaHeaders.OFFSET).toString());

      String a = null;
      a.substring(0, 3); // causing null pointer exception for testing purposes
      sendAck(message);
 }
```
If your use case requires manual acknowledgment, then you probably need to catch the exception, ack it, then rethrows the exception from the `StreamListener` to dispatch the record to the DLQ. 
I think this is the issue you are running in your test case `#1`.

Once this is addressed, you may still see the issue that you are seeing in test case `#2`.  This is because you are setting `max.poll.interval.ms` to 5000. Therefore, if you have a lot of records published to the topic before the app starts, then the consumer won't be polled within the interval (as the retries are in progress on the main consumer thread). In order to address this, you have to increase this max polling interval. 

The following application and setup work fine with both your scenarios. Note that, I am using `auto-commit-offset` to `true`. Do you have a compelling use-case to set this to `false`?

```
spring:
  cloud:
    stream:
      default:
        group: my-consumer-group
      kafka:
        binder:
          brokers:
            - 127.0.0.1:9092
        bindings:
          input:
            consumer:
              auto-commit-offset: true
              autoCommitOnError: true # by default it it same as enableDlq
              enableDlq: true
              dlqName: test-dlq
              configuration:
                max.poll.interval.ms: 30000
      bindings:
        input:
          destination: test-topic
```

````
@SpringBootApplication
@EnableBinding(Sink.class)
public class KafkaConsumer {

	public static void main(String[] args) {
		SpringApplication.run(KafkaConsumer.class, args);
	}

	@StreamListener(value = Sink.INPUT)
	public void listen(Message<String> message) throws InterruptedException {
		System.out.println("log this message : " + message.getPayload() + " offset : " + message.getHeaders().get(KafkaHeaders.OFFSET).toString());

		//Application's logic. 
	}
}
```

**Comment by jskim1991** [comment]
@sobychacko 
I have stated that NPE is to force an exception so it won't get acked. That way I can test if offset is increased solely on DLQ. `max.poll.interval.ms` is limited for other testing purposes. 

The reason I want to use manual commit is that in my business case, some services require more processing time than auto commit window. And it varies so I cannot just pick a magic number and let offset be committing on failures. 

That being said, if an error is occurred within the auto commit window, retries would happen. But however if a process is going on longer than auto commit window and process fails, then wouldn't that move the offset to the next?

**Comment by sobychacko** [comment]
@jskim1991 Ok. That makes sense. I wasn't following the fact that you were deliberately not acking it. In that case, the offset on the main consumer won't move forward at all, since you disabled `auto-commit-offset`, but you will see that the DLQ works as expected. Maybe, I still don't follow the underlying issue that you are running into? The way I understood this is that you are not seeing the offset going forward in the consumer group, correct? For that the manual ack needs to happen since you disabled auto commit.  Even when you manually ack, this may still fail because of that `max.poll.interval.ms` setting. I saw that the commit fails exception thrown (due to the rebalance) from Spring Kafka while debugging the code that you shared above.

**Comment by jskim1991** [comment]
@sobychacko 
The underlying issue is this
> Before starting the consumer app, send a few records. Then, start the consumer app. It will go through each record and send to DLQ. It should stop here like the first test case. However, once it iterates over all the records, it will go back to the starting offset and write it to DLQ again and again (it loops). When testing with 3 different records, I saw my DLQ was being loaded with those 3 records repeatedly.

My DLQ topic is getting infinite amount of repeated records. (`# of records` * `iterations`)

> Even when you manually ack, this may still fail because of that max.poll.interval.ms setting. I saw that the commit fails exception thrown (due to the rebalance) from Spring Kafka while debugging the code that you shared above.

while I was debugging, I didn't see any CommitFailedException. However, you are correct. I put `max.poll.interval.ms` there just to test CommitFailedException. 

Can you try with the followings:
1. send a few records
2. start your consumer (using manual commit)
3. let it sit and watch the consumer send infinitely to DLQ topic.

**Comment by sobychacko** [comment]
@jskim1991 I did reproduce the behavior that you are describing with the manual ack initially i.e, the infinite send. That is when I saw that commit fail exception. However, with the following, I am not able to reproduce and see that the offsets are moving forward as expected.

```
@StreamListener(value = Sink.INPUT)
	public void listen(Message<String> message) throws InterruptedException {
		System.out.println("log this message : " + message.getPayload() + " offset : " + message.getHeaders().get(KafkaHeaders.OFFSET).toString());

		String a = null;
		try {
			a.substring(0, 3); // causing null pointer exception for testing purposes
		}
		catch (Exception e) {
			sendAck(message);
			throw e;
		}
	}

	public void sendAck(Message<String> message) {
		Acknowledgment acknowledgment = message.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class);
		if (acknowledgment != null)  {
			try {
				acknowledgment.acknowledge();
				System.out.println("manual commit complete");
			}
			catch (Exception e)  {
				throw e; // retry
			}
		}
	}
```

```
spring:
  cloud:
    stream:
      default:
        group: my-consumer-group-1
      kafka:
        binder:
          brokers:
            - 127.0.0.1:9092
        bindings:
          input:
            consumer:
              auto-commit-offset: false
              autoCommitOnError: true # by default it it same as enableDlq
              enableDlq: true
              dlqName: test-dlq-1
      bindings:
        input:
          destination: test-topic-1
```
