### ISSUE TITLE
bind different type of topics in the same broker not working

### ISSUE THREAD

**Issue by AlvinYueChao** [spring-cloud/spring-cloud-stream-binder-kafka#874]
In my sceniario, I have two different type of topics in the same broker. the first is json output topic and the second is avro input topic. These two topics have different username and password. so I want to use binders to setup the producer and consumer configuration but it not work. 
It works fine when I only configure the input binder or output binder in the same application.yml.
I have attached my configuration, maven dependencies and related error message log, 
Please help to check whether it is a issue.
[scenario.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4404573/scenario.zip)

**Comment by AlvinYueChao** [comment]
anyone can help advise on it ?

**Comment by AlvinYueChao** [comment]
hi team. today I debugged my application into org.springframework.cloud.stream.binding.BindingService. when the running cursor stopped at Line 232 `return this.binderFactory.getBinder(binderConfigurationName, bindableType);`, from the varables window, I can see that each topic within the bindings has the correct mapped binder name. then I let the program keep running and then I got SaslAuthenticationException from kafka. If I only configure one binder and one bindings, the error would be gone.

**Comment by sobychacko** [comment]
@AlvinYueChao I will have a look at this today.

**Comment by sobychacko** [comment]
@AlvinYueChao I am not sure what the issue is. From that zip file that you attached ^^, I see an exception - something as below. 
```
org.springframework.cound.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:435)
    at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:97)
    at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:142)
    at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:144)
    at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:122)
    at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:254)
    at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
    at java.util.LindedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
    at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(InputBindingLifecycle.java:48)
    ...
Caused by: java.lang.IllegalArguementException: A list of partitions must be privided 
	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.jave:432)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.jave:132)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:382)
	... 24 common frames omitted
````
However, in your above analysis, you seem to imply that you are getting a `SaslAuthenticationException`.  Please have a look at this configuration from our samples repository: https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/multi-binder-samples/kafka-multi-binder-jaas/src/main/resources/application.yml.
That sample indeed takes `jaas.options` in the configuration. I suggest starting with that sample and compare notes with your configuration and see where it deviates from the sample.

Even after trying that sample, if you are still having trouble running it, could you provide a small standalone application for us to debug with instructions on how we can reproduce the issue?

**Comment by AlvinYueChao** [comment]
@sobychacko these two exceptions occured in the same case. firstly, `SaslAuthenticationException` occured then I got `org.springframework.cound.stream.binder.BinderException: Exception thrown while starting consumer`. In my case, the producer topic and consumer have different message type and differnent username and password. if these two topics have the same jaas configuration, the issue would not occur. I have attached my use case based on the [sample repository](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/multi-binder-samples/kafka-multi-binder-jaas/src/main/resources/application.yml.)
[reproduce-application.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4418596/reproduce-application.zip)

**Comment by sobychacko** [comment]
@AlvinYueChao I will run an application with your configuration and get back to you.

**Comment by sobychacko** [comment]
@AlvinYueChao I was able to reproduce your issue. I am still investigating to see if this is a bug in the binder. Basically, the second time a binder context is created (from the multi binder context), the jass properties specified in that context are not properly propagated to the jaas handler. I can see that the `KafkaJaasLoginModuleInitializer` bean is properly created from the multi binder context. I will try to debug more/discuss with the team internally and find out what the resolution is. Thanks for bringing this to our attention.

**Comment by AlvinYueChao** [comment]
@sobychacko after deeply debuging, I think I found the root cause. What I used is JDK 1.8. at `javax.security.auth.login.Configuration public static Configuration getConfiguration()`, it uses synchronized and null-check to make sure the login configuration only be set once. Event though the spring-cloud-stream framework can support multiple jaas configurations syntax, the final effective configuration would only be the first one. I think if spring-cloud-stream-binder-kafka should disable multiple jaases syntax to avoid this issue ? or we should raise this issue to Java community ?

**Comment by sobychacko** [comment]
@AlvinYueChao We also came to sort of the same conclusion. The access credentials are set statically per classloader, thus the jaas configuration set through the second binder context is ignored. We cannot simply pass it along, as jaas won't allow resetting that. As you said, if they make it relaxed, then it will work, but I am not sure how feasible it is to address those issues at the core java security foundation. In fact, there might be valid reasons why it is designed that way.

We can potentially fix this in the binder by loading the binder contexts in separate classloaders. That will make sure that the second update is visible for the access controller. However, we won't be able to make such a major change in 3.0.x SR releases. It has to wait until the next major release 3.1, as this needs to be tested thoroughly for any side effects. 

In the meantime, may I ask, why do you have separate access controls for the two topics? Are they on two different Kafka clusters? Or the same cluster, but different login credentials? If you can make the logins the same, that can be used as a workaround.

**Comment by AlvinYueChao** [comment]
@sobychacko In my case, these two topics are on the same kafka cluster, but different logic credentials. I have skipped this issue by adding read permission for the one credential. so that the same user can access the different topics. Thanks for your help. Please let me know the update about your changes if you decide to do it.

**Comment by sobychacko** [comment]
@AlvinYueChao We will keep this issue open for trying to come up with some alternatives in 3.1.

**Comment by sabbyanandan** [comment]
Hi, @AlvinYueChao. As pointed out by @sobychacko previously, perhaps the more uncomplicated and easy to maintain solution here would be to use the same login credentials for both the users. Once we get into RBAC'ing at individual topics and user impersonation, it gets very complicated. 

Let us know if you have any other thoughts/concerns. I will close it for now.

**Comment by sobychacko** [comment]
Just wanted to close the loop on this issue. Kafka [KIP-85](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=65873665) implementation has a solution for this issue. Here is the gist: Instead of using the binder provided jaas configuration or setting the `java.security.auth.login.config` property, use the `sasl.jaas.config` property which takes precedence over other methods. By using `sasl.jaas.config`, you can override the restriction placed by JVM in which a static security context is used and the first context/configuration always wins. For example, the following configuration is from a single application in which it connects to two different Kafka Clusters. 
```
spring.cloud.stream:
    binders:
        kafka1:
          type: kafka
          environment:
             spring:
               cloud:
                 stream:
                  kafka:
                    binder.brokers: localhost:9092
                    binder.configuration.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\";"
        kafka2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9093
                      configuration.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"foo\" password=\"foo-secret\";"
    kafka.binder:
        configuration:
          security.protocol: SASL_PLAINTEXT
          sasl.mechanism: PLAIN
```

**Comment by YuryYaroshevich** [comment]
Hello!
I'm having similar issue but with ssl certificates.
```
binders:
        kafka-1:
          type: kstream
          defaultEnvironment: false
          environment:
            spring.cloud.stream.kafka.streams.binder:
              autoCreateTopics: false
              brokers: broker1.net:9093,broker2.net:9093,broker3.net:9093
              configuration:
                security.protocol: SSL
                ssl.truststore.location: trustore1.jks
                ssl.truststore.password: secret-pass
                ssl.keystore.location: keystore1.jks
                ssl.keystore.password: secret-pass
                ssl.key.password: secret-pass
        kafka-2:
          type: kstream
          defaultEnvironment: false
          environment:
            spring.cloud.stream.kafka.streams.binder:
              autoCreateTopics: false
              brokers: broker1.net:9093,broker2.net:9093,broker3.net:9093
              configuration:
                security.protocol: SSL
                ssl.truststore.location: trustore3.jks
                ssl.truststore.password: secret-pass
                ssl.keystore.location: keystore3.jks
                ssl.keystore.password: secret-pass
                ssl.key.password: secret-pass
         ...
         kafka-N:
         ....       
```
Values of kafka-1 for `ssl.truststore.location` and `ssl.keystore.location` are used for all binders. Is there similar remedy to ssl configuration?
More about my case here: https://stackoverflow.com/questions/76737736/why-im-getting-topicauthorizationexception-when-multiple-kafka-binders-enabled?noredirect=1#comment135291081_76737736
