### ISSUE TITLE
Using classpath in location of ssl configs for Kafka producer/consumer

### ISSUE THREAD

**Issue by djwilli3** [spring-cloud/spring-cloud-stream-binder-kafka#890]
Same error for both keystore and truststore.  

Example application.yml
```yaml
kafka:
        binder:
          brokers: kafkaurl
          defaultBrokerPort: 9093
          configuration:
            security:
              protocol: SSL
            ssl:
              keystore:
                location: classpath:applicationsamplekeystore.jks
                password: password!
              truststore:
                location: classpath:applicationsampletruststore.jks
                password: password!
              key:
                password: password!
```
Stack error:
06-05-2020 12:25:45.828 [task-scheduler-2] ERROR o.a.k.c.s.ssl.SslEngineBuilder.lastModifiedMs - Modification time of key store could not be obtained: classpath:classpath:applicationsampletruststore.jks
java.nio.file.NoSuchFileException: classpath:applicationsampletruststore.jks
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)

thanks
