### ISSUE TITLE
Dynamic destinations with mutiple binders:

### ISSUE THREAD

**Issue by ennala** [spring-cloud/spring-cloud-stream-binder-kafka#913]
Sorry for posting it here.. couldnt get much help from SO. Please pardon me for that.

I need to consume from different topics on one kafka cluster and forward the message to same topic on another kafka cluster/clusters depending on the business logic.

I found an example for BinderAwareChannelResolver for solving destinations dynamically in the documentation .... but not able to understand how to make it work with multiple binders. Appreciate any inputs on how to configure BinderAwareChannelResolver with multiple binders.

Here is more detailed explanation of what I am trying to achieve.

Consume from topic1,topic2,topic3 etc from kafka cluster1.

Forward the message to same topic to kafka cluster 2 if it meets criteria 1.

Forward the message to same topic to kafka cluster 2 if it meets criteria 2.

**Comment by sobychacko** [comment]
@ennala Sorry for not responding to your question on SO. We might have missed it. Do you have a link to that? 

You can use the newly introduced `StreamBridge` instead of `BinderAwareChannelResolver` which is deprecated. You need to use this in addition to the multi binder configuration. 

Here are some templates and pseudo-code:

Assuming that, you have two input topics and two output topics. You can use Tuple[N] classes from Project Reactor for doing this.

```
@Autowired StreamBridge streamBridge;

@Bean
public  Consumer<Tuple2<String, String>> multiInWithDynamicDestination() {
	return tuple -> {
		String first = tuple.getT1();
		String second = tuple.getT2();
              if (first == "some conditions met") {
                streamBrige.send("foo-out-0", first); // foo-out-0 is the binding name.
             }
            else if (second == "some condition...") {
                streamBrige.send("bar-out-0", second); // bar-out-0 is the binding name.
            }				
	};
}
```

Configuration:
```
spring.cloud.stream.source=foo-out-0;bar-out-0
spring:
  cloud:
    stream:
      bindings:
        multiInWithDynamicDestination-in-0:
          destination: dest-1
          binder: kafka1
        multiInWithDynamicDestination-in-1:
          destination: dest-2
          binder: kafka1
        foo-out-0:
          destination: dest-1
          binder: kafka2
       bar-out-0:
          destination: dest-2
          binder: kafka2
      function:
        definition: multiInWithDynamicDestination
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: ${kafkaBroker1}
                      zkNodes: ${zk1}
        kafka2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: ${kafkaBroker2}
                      zkNodes: ${zk2}
```

See [this test](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/StreamBridgeTests.java) for more usage examples for `StreamBridge`.

See [this sample](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/multi-binder-samples/multi-binder-two-kafka-clusters/src/main/resources/application.yml) for configuring multi binders.
