### ISSUE TITLE
Dynamic Kafka host URI

### ISSUE THREAD

**Issue by frank72833** [spring-cloud/spring-cloud-stream-binder-kafka#920]
Hi,

We are currently running microservices using spring boot and connecting with AWS MSK (Kafka) using spring cloud.

We have a Kafka cluster running on AWS MSK and we point a "alias" in our K8s cluster to the MSK brokers URIs. 

Making it short, KAFKA_HOST will be resolved to the brokers URI.

In our spring application properties we have the following:
```
cloud:
    stream:
        kafka:
            binder:
               brokers: ${KAFKA_HOST:localhost:9092}
```

Until here all works beautifully! However, we needed to migrate to a different MSK cluster and we swapped the URIs on the K8s alias that will make KAFKA_HOST to resolve in different URIs. 

Unfortunately, the spring cloud library keeps trying to reconnect to the old URIs and it doesn't refresh to the newer ones. We needed to restart the applications and it worked again just fine.

Does the client resolve the provided URI at the start and caches it forever? Is there a way to make that URI dynamic?

Many thanks,
Kind regards.
