### ISSUE TITLE
applicationId issue on Multiple Inputs

### ISSUE THREAD

**Issue by jomach** [spring-cloud/spring-cloud-stream-binder-kafka#929]
Hi Everyone, 

I'm getting this exception: 
```
Caused by: org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException: Property spring.kafka.streams.application-id with value 'null' is invalid: This property is mandatory and fallback 'spring.application.name' is not set either.
```
My yaml: 
```
spring.cloud.stream:
    bindings:
        priceChannel:
            destination: price

        mappingChannel:
            destination: products-mappings
        stockChannel:
            destination: stock
        productsMergedChannel:
            destination: products-merged
    kafka:
        binder:
            brokers: 'localhost:9092,localhost:9093'
            autoAddPartitions: true
        # Kafka Streams Config (akka kafka streams)
        # Multiple StreamListener see KafkaStreamsExtendedBindingProperties.java
        streams:
            bindings:
                priceChannel:
                    consumer:
                       applicationId: merge_stream_price
.......

```

I don't understand why is not working. From the docs https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/3.0.6.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#_kafka_streams_application_id it should work
