### ISSUE TITLE
Serde For stream Producer.

### ISSUE THREAD

**Issue by uselvvi** [spring-cloud/spring-cloud-stream-binder-kafka#937]
I use these dependencies.

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
```
My producer & processor:

```
@Bean
public Supplier<Flux<Long>> interval(){
	return () -> Flux.interval(Duration.ofSeconds(1));
}

@Bean
public Function<KStream<String, Long>, KStream<String, Long>> processor(){
	return kstream -> kstream
						.peek((k, v) -> System.out.println("Processing : " + v));
}  
```
My config:
```
spring.cloud.stream:
  function:
    definition: interval;processor
  bindings:
    interval-out-0:
      destination: interval
    processor-in-0:
      destination: interval
```

The producer writes into the kafka topic successfully. But it seems to be in byte[]. Because of that processor is unable to convert that to Long,. How to use Serde here. I have used various options. nothing seems to work.

This does not seem to help

```
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=org.apache.kafka.common.serialization.Serdes$LongSerde
