### ISSUE TITLE
KTable materialization - messages sometimes missing

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-stream-binder-kafka#938]
# Problem
I'm having a strange issue that I need some help with. Essentially, messages seem to be missing from a KTable materialization. My application receives messages on an input topic and is configured via the properties file to materialize these messages to a state store called "store-1". I also manually set up a second state store called "store-2" and write to it in the processor using the same key as message in "store-1". I set up two punctuations which perform read and write operations on the state stores also.

When my application is running it receives messages on the input topic and processes them, however, when the puncutation tries to read out the message via its key from "store-1" (the store from the KTable) _the message is sometimes missing from the store_, i.e. there is no entry with that key. I do not have any clean up configured for the Kafka topic. This issue happens intermittently: sometimes the message with a given key will be in the state store materialized from the KTable and other times it won't. Note that each message sent has a unique key.

My first thought was this that the problem was due to partitioning of the two _changelog topics_, so I have implemented _copartitioning_ by ensuring both state stores use the same keys. This has not resolved the problem.

From the outside it appears that the materialization of the KTable sometimes persists a message, and other times it does not. Any idea what is going on here? Have I overlooked something?

# Dependencies
I am constrained to use older versions of the libraries:

* Spring Cloud Dependencies version: Greenwich.SR6
* Spring Boot version: 2.1.15.RELEASE

# Example Code
My stream listener class is set up like so:

```
    @Override
    @StreamListener(target = INPUT_CHANNEL)
    public void consumeMessage(KTable<String, JsonNode> messageKTable) throws Exception {
        addStateStore();
        messageKTable.toStream().process(() -> new MyProcessor(), "store-1", "store-2");
    }

    private void addStateStore() throws Exception {
        StreamsBuilderFactoryBean factoryBean = context.getBean("&stream-builder-consumeMessage", StreamsBuilderFactoryBean.class);
        StoreBuilder storeBuilder = Stores.keyValueStoreBuilder(
                Stores.persistentKeyValueStore("store-2"), Serdes.String(), new MyValueSerde());
        factoryBean.getObject().addStateStore(storeBuilder);
    }
```

A separate class has my processor code:

```
    private ProcessorContext context;

    @Override
    public void init(ProcessorContext context) {
        this.context = context;
        configurePunctuate(firstSchedule);
        configurePunctuate(secondSchedule);
    }

    @Override
    public void process(String messageId, JsonNode message) {
        // Do stuff and add message to "store-2" using put() on the state store object
    }

    private void configurePunctuate(long scheduleMillis) {
        context.schedule(scheduleMillis, PunctuationType.WALL_CLOCK_TIME, timestamp -> {
            // Do stuff with messages from both state stores using all(), get() and delete() methods
        }
    }

```

My properties file:

```
spring:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    stream:
      default:
        group: myGroup

      kafka:
        streams:
          bindings:
            inputChannel:
              consumer:
                applicationId: myAppId
                materializedAs: store-1
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.foo.MyValueSerde.class

      bindings:
        inputChannel:
          destination: myTopic
```
