### ISSUE TITLE
Unable to create to multiple binders with SASL_SSL protocol.

### ISSUE THREAD

**Issue by manas8** [spring-cloud/spring-cloud-stream-binder-kafka#944]
Hello guys,

I have been facing problem creating multiple ssl-secured kafka binders. No problems with multiple unsecured (PLAINTEXT protocol) binders. 

More details in the following [link](https://stackoverflow.com/questions/63185259/spring-cloud-stream-binder-kafka-unable-to-create-multiple-kafka-binders-with). 

Please help fix the issue. I have used springboot-2.2.8 and latest spring-cloud-stream-dependencies version Horsham.SR6.

**Comment by manas8** [comment]
Can anyone look into it please. Let me know if the question has to be edited in particular way to be looked into it. All the information has been provided in the link though.

**Comment by laxika** [comment]
@sobychacko  I have the same issue. Could this be related to #874 or #924? As far as I see you can't use more than one `jaas` config with the binder. Is this right?

**Comment by sobychacko** [comment]
@laxika I was thinking about the same thing. Since there is only a single security context per JVM for the application (since it is shared through some static contexts), it is hard to have separate `jaas` configs per binder as detailed [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/874#issuecomment-608466978). I still would like to confirm though that this is really the issue or not and that's I raised a comment [here](https://stackoverflow.com/questions/63185259/spring-cloud-stream-binder-kafka-unable-to-create-multiple-kafka-binders-with#comment111823260_63185259). Since a few different use cases have come up pointing to the same potential issue, I think we need to think about a viable alternative. Any suggestions are welcomed.

**Comment by pidoubleyou** [comment]
I have the same issue. 

I made some tests with the sample [kafka-multi-binder-jaas](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multi-binder-samples/kafka-multi-binder-jaas):
* different brokers, same jaas configuration 🆗 
* different brokers, different jaas configuration ❌ 
* same broker, same jaas configuration 🆗 
* same broker, different jaas configuration ❌ 
* different brokers, one with jaas, one with security 🆗 

Hope this helps.

**Comment by sobychacko** [comment]
I wanted to give an update on this issue. Instead of using the binder provided `jaas` configuration or setting the `java.security.auth.login.config` property, use the `sasl.jaas.config` property which takes precedence over other methods. By using `sasl.jaas.config`, you can override the restriction placed by JVM in which a static security context is used, thus ignoring any subsequent `JAAS` configurations after the first one. 

The following configuration is from a single application in which it connects to two different Kafka Clusters using `sasl.jaas.config`. 

```
spring.cloud.stream:
    binders:
        kafka1:
          type: kafka
          environment:
             spring:
               cloud:
                 stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
                      configuration.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\";"
        kafka2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9093
                      configuration.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"foo\" password=\"foo-secret\";"
    kafka.binder:
        configuration:
          security.protocol: SASL_PLAINTEXT
          sasl.mechanism: PLAIN
```
Please see this [updated sample](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/multi-binder-samples/kafka-multi-binder-jaas) for how this configuration work in a complete application.
