### ISSUE TITLE
Configure the consumer properties programatically

### ISSUE THREAD

**Issue by ghahramani** [spring-cloud/spring-cloud-stream-binder-kafka#960]
Hi,

I tried to set my consumer properties programmatically instead of using `application.yml` but couldn't find anyway, I want to follow the example in this ticket https://github.com/spring-projects/spring-kafka/issues/897 which shows how you can do manual wiring in your interceptor. If I define the interceptor like below, it works

```
spring:
     cloud:
         kafka:
             binder: 
                   consumer-properties:
                            interceptor.classes: xxx.yyy.zzz.MyInterceptor
```

But I couldn't find any way to do set this while creating Bean. I was told by @garyrussell to raise a feature request here.

So what I am trying to do is, having spring boot bean in spring cloud function interceptor.
