### ISSUE TITLE
Unable to override default confluent monitoring interceptor properties

### ISSUE THREAD

**Issue by nsshashank91** [spring-cloud/spring-cloud-stream-binder-kafka#962]
```yaml
spring:
   cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            confluent:
              monitoring:
                interceptor:
                  topic: my_intercept_topic
          producerProperties:
              interceptor:
                classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
          consumerProperties:
              interceptor:
                classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
```

I want to override default intercept confluent monitoring topic from _confluent-monitoring to my_intercept_topic. But unable to do so when using spring-cloud-stream-binder-kafka

**Comment by garyrussell** [comment]
You cannot set arbitrary properties via `...binder.configuration`, only those properties defined by `ProducerConfig` and `ConsumerConfig`.

You can, however, set arbitrary propertied via the `...binder.producerProperties` (and `consumerProperties`).

So

```
spring:
   cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          producerProperties:
            interceptor:
              classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
            confluent:
              monitoring:
                interceptor:
                  topic: my_intercept_topic
          consumerProperties:
            interceptor:
              classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
            confluent:
              monitoring:
                interceptor:
                  topic: my_intercept_topic
```

should work ok.
